-- db/schema/types/ic_microcontrollers.sql
-- Canonical parametric tail for ic_microcontrollers (ic_microcontrollers).
-- Note: pin_count is a core field — not repeated here.
    family TEXT,
    core TEXT,
    supply_voltage_min REAL,
    supply_voltage_max REAL,
    flash_size TEXT,
    eeprom_size TEXT,
    ram_size TEXT,
    architecture_bits INTEGER,
    max_clock TEXT,
    active_current TEXT,
    sleep_current TEXT,
    gpio_count INTEGER,
    uart_count INTEGER,
    i2c_count INTEGER,
    spi_count INTEGER,
    usb_count INTEGER,
    can_count INTEGER,
    eth_count INTEGER,
    timer_count INTEGER,
    pwm_count INTEGER,
    dma_count INTEGER,
    adc_count INTEGER,
    adc_resolution TEXT,
    dac_count INTEGER,
    special_features TEXT