DROP TABLE IF EXISTS voltage_reference;

CREATE TABLE voltage_reference (
    -- Core fields (shared across all component tables)
    unique_id TEXT PRIMARY KEY,
    part_locator TEXT,
    mpn TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    variant TEXT,
    package TEXT,
    value TEXT,
    description TEXT,
    datasheet TEXT,
    manufacturer_link TEXT,
    kicad_symbol TEXT,
    kicad_footprint TEXT,
    altium_symbol TEXT,
    altium_footprint TEXT,
    lifecycle_status TEXT DEFAULT 'Active',
    rohs TEXT DEFAULT 'no',
    rohs_document_link TEXT,
    allow_substitution TEXT DEFAULT 'no',
    tracking TEXT DEFAULT 'no',
    standards_version TEXT DEFAULT 'v1.0',
    bom_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT,
    source TEXT DEFAULT 'static',
    dump_priority INTEGER DEFAULT 1,
    tier INTEGER DEFAULT 2,
    keywords TEXT DEFAULT '',
    sim_model_type TEXT,
    sim_device TEXT,
    sim_pins TEXT,
    sim_model_file TEXT,
    sim_params TEXT,
    pin_count TEXT,
    component_height TEXT,
    exclude_from_bom BOOLEAN NOT NULL DEFAULT 0,
    temp_operating_min REAL,
    temp_operating_max REAL,
    temp_storage_min REAL,
    temp_storage_max REAL,
    temp_soldering REAL,

    -- Type-specific fields (voltage reference)
    reference_type TEXT,           -- 'series' | 'shunt',
    output_voltage TEXT,           -- nominal output, e.g. '5V', '2.5V', '4.096V', or 'adjustable',
    output_voltage_options TEXT,   -- csv of the family's available fixed outputs,
    initial_accuracy TEXT,         -- e.g. '±0.05%' or '±2.5mV',
    temperature_coefficient TEXT,  -- drift, e.g. '2ppm/°C',
    output_noise TEXT,             -- 0.1-10Hz noise, e.g. '0.25ppm p-p' / '3µVp-p',
    output_current TEXT,           -- series: max source/sink; shunt: operating current,
    input_voltage_min REAL,        -- series supply min (V),
    input_voltage_max REAL,        -- series supply max (V),
    dropout_voltage TEXT,          -- series ref input-output headroom,
    line_regulation TEXT,
    load_regulation TEXT,
    long_term_drift TEXT,          -- e.g. 'ppm/√khr' or 'ppm/1000hr',
    adjustable TEXT                -- 'yes' | 'no'
);
