#!/usr/bin/env python3
"""Harvest Analog Devices / Linear Technology linear regulators (LDOs).

Datasheet-driven; same BASE-specs x VARIANTS-packages shape as the ic_opamp
generators. Datasheets live in the central store at datasheets/analog-devices/.
LT3045 has dedicated KiCad symbols (LT3045xDD / LT3045xMSE), grep-verified.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
import re
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("voltage_regulator_generated_300_adi_regulators.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "variant", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint",
    "rohs", "allow_substitution", "tracking", "source", "dump_priority", "tier",
    "keywords", "pin_count", "regulator_type", "output_voltage", "output_voltage_min",
    "output_voltage_max", "output_current", "input_voltage_min", "input_voltage_max",
    "dropout_voltage", "quiescent_current", "output_noise", "psrr", "line_regulation",
    "load_regulation", "accuracy", "adjustable", "features",
]

DEFAULTS = {
    "manufacturer": "Analog Devices",
    "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
    "source": None, "dump_priority": 0, "tier": 2,
}

DFN12 = "Package_DFN_QFN:DFN-12-1EP_3x3mm_P0.45mm_EP1.65x2.38mm"
MSOP12 = "Package_SO:MSOP-12_3x4.039mm_P0.65mm"

BASE = {
    "LT3045": dict(
        datasheet="${TERRA_EDA_LIB}/datasheets/analog-devices/lt3045.pdf",
        description="Analog Devices LT3045 20V, 500mA ultralow-noise (0.8µVRMS), ultrahigh-PSRR (76dB at 1MHz) adjustable LDO",
        manufacturer_link="https://www.analog.com/en/products/lt3045.html",
        keywords="ldo,linear-regulator,low-noise,high-psrr,adjustable,low-dropout,programmable-current-limit,lt3045",
        regulator_type="LDO", output_voltage="adjustable",
        output_voltage_min=0.0, output_voltage_max=15.0, output_current="500mA",
        input_voltage_min=1.8, input_voltage_max=20.0, dropout_voltage="260mV",
        quiescent_current="2.3mA", output_noise="0.8µVrms (10Hz-100kHz)",
        psrr="76dB at 1MHz", line_regulation="0.5µV/V", load_regulation="0.1mV (1-500mA)",
        accuracy="±1%", adjustable="yes",
        features="current-limit,thermal-shutdown,programmable-current-limit,power-good,reverse-battery-protection,precision-enable-uvlo,parallelable"),
}

# (package, mpn, pin_count, kicad_symbol, kicad_footprint, note)
VARIANTS = {
    "LT3045": [
        ("DFN-12", "LT3045EDD", "12", "Regulator_Linear:LT3045xDD", DFN12, ""),
        ("MSOP-12", "LT3045EMSE", "12", "Regulator_Linear:LT3045xMSE", MSOP12, ""),
    ],
}


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = ["-- Terra EDA Library - ADI/LT linear regulators (LDO)",
             f"-- Generated by {CREATED_BY}. dump_priority=0, source=NULL.", "",
             "BEGIN TRANSACTION;", ""]
    seen, needs_work = set(), []
    for value, base in BASE.items():
        for package, mpn, pin_count, ksym, kfp, note in VARIANTS[value]:
            uid = f"Analog_Devices-{mpn}"
            if uid in seen:
                raise SystemExit(f"duplicate unique_id: {uid}")
            seen.add(uid)
            pkgtoken = re.sub(r"[^a-z0-9]+", "-", package.lower()).strip("-")
            row = {**DEFAULTS, **base, "unique_id": uid,
                   "part_locator": f"ldo-{base['output_current'].lower()}-{pkgtoken}",
                   "mpn": mpn, "variant": package, "package": package, "value": value,
                   "description": f"{base['description']}, {package}",
                   "kicad_symbol": ksym, "kicad_footprint": kfp, "pin_count": pin_count}
            if ksym is None or kfp is None:
                needs_work.append(f"{value} {package}: {note}")
            vals = ", ".join(sql(row.get(c)) for c in COLS)
            lines.append(f"INSERT INTO voltage_regulator ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(seen)} rows across {len(BASE)} parts")
    if needs_work:
        print(f"  {len(needs_work)} row(s) need work (NULL symbol/footprint):")
        for w in needs_work:
            print(f"    - {w}")


if __name__ == "__main__":
    main()
