#!/usr/bin/env python3
"""Harvest curated test-point parts from the abc4-spiro mainboard into native terra.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("test_points_generated_300_spiro_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "tags", "pin_count",
    "tp_style", "pad_diameter_mm", "mount", "color",
]

PARTS = [
    {
        "unique_id": "Keystone-5017", "part_locator": "testpoint-smt-loop",
        "mpn": "5017", "manufacturer": "Keystone Electronics", "value": "Test Point",
        "description": "Keystone 5017 miniature SMT PC test point, loop style",
        "datasheet": "https://www.keyelco.com/product-pdf.cfm?p=1355",
        "manufacturer_link": "https://www.keyelco.com",
        "kicad_symbol": "Connector:TestPoint",
        "kicad_footprint": "terra-test-points:TestPoint_Pad_3.43x1.78mm",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "tags": "test-point,mechanical", "pin_count": "1",
        "tp_style": "smt-pad", "pad_diameter_mm": None, "mount": "SMT", "color": None,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - test_points harvest from abc4-spiro mainboard",
        f"-- Curated test-point parts ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO test_points ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
