"""Shared emit helpers for diodes_tvs generators.

Each generator builds `rec` dicts (keys = a subset of COLS; missing keys become
NULL) and calls insert(); write() wraps the rows in a transaction. Output is
dump_priority=0 / source=NULL — generated, never dumped to static SQL.
"""
from pathlib import Path

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "temp_operating_min", "temp_operating_max", "temp_storage_min",
    "temp_storage_max", "directionality", "standoff_voltage",
    "breakdown_voltage_min", "breakdown_voltage_max", "breakdown_test_current",
    "clamping_voltage", "peak_pulse_current", "peak_pulse_power",
    "leakage_current", "capacitance",
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def insert(rec):
    vals = ", ".join(sql(rec.get(c)) for c in COLS)
    return f"INSERT INTO diodes_tvs ({', '.join(COLS)}) VALUES ({vals});"


def write(output_file, created_by, rows, title):
    lines = [
        f"-- Terra EDA Library - {title}",
        f"-- Generated by {created_by}. dump_priority=0, source=NULL: not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
        *rows,
        "",
        "COMMIT;",
        "",
    ]
    Path(output_file).write_text("\n".join(lines))
    print(f"Generated {Path(output_file).name}: {len(rows)} parts")
    return len(rows)
