CREATE TABLE diodes_tvs (
    unique_id TEXT PRIMARY KEY,
    part_locator TEXT,
    mpn TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    variant TEXT,
    package TEXT,
    value TEXT,
    description TEXT,
    datasheet TEXT,
    manufacturer_link TEXT,
    kicad_symbol TEXT,
    kicad_footprint TEXT,
    altium_symbol TEXT,
    altium_footprint TEXT,
    lifecycle_status TEXT DEFAULT 'Active',
    rohs TEXT DEFAULT 'no',
    rohs_document_link TEXT,
    allow_substitution TEXT DEFAULT 'no',
    tracking TEXT DEFAULT 'no',
    standards_version TEXT DEFAULT 'v1.0',
    bom_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT,
    source TEXT DEFAULT 'static',
    dump_priority INTEGER DEFAULT 1,
    tier INTEGER DEFAULT 2,
    keywords TEXT DEFAULT '',
    sim_model_type TEXT,
    sim_device TEXT DEFAULT 'D',
    sim_pins TEXT DEFAULT '1=K 2=A',
    sim_model_file TEXT,
    sim_params TEXT,
    pin_count TEXT,
    component_height TEXT,
    exclude_from_bom BOOLEAN NOT NULL DEFAULT 0,
    temp_operating_min REAL,
    temp_operating_max REAL,
    temp_storage_min REAL,
    temp_storage_max REAL,
    temp_soldering REAL,
    directionality TEXT,          -- unidirectional | bidirectional,
    standoff_voltage TEXT,        -- Vrwm reverse standoff / working voltage,
    breakdown_voltage_min REAL,   -- Vbr min at IT (V),
    breakdown_voltage_max REAL,   -- Vbr max at IT (V),
    breakdown_test_current TEXT,  -- IT, the Vbr test current,
    clamping_voltage TEXT,        -- Vc max at Ipp,
    peak_pulse_current TEXT,      -- Ipp (10/1000 us),
    peak_pulse_power TEXT,        -- Ppp peak pulse power,
    leakage_current TEXT,         -- IR max at Vrwm,
    capacitance TEXT,             -- Cj typ (pF) where specified,
    channels INTEGER,             -- protected lines (1 = discrete, >1 = array),
    esd_contact_kv TEXT           -- IEC 61000-4-2 contact-discharge ESD rating
);
