-- Terra EDA Library - ic_analog Table
-- Number of components: 12
-- Sorted by: part_id
--
-- This file is auto-generated and suitable for git tracking.
-- Rows are sorted deterministically to ensure consistent diffs.
--

DROP TABLE IF EXISTS ic_analog;

CREATE TABLE ic_analog (
            
        part_id TEXT PRIMARY KEY,
        mpn TEXT NOT NULL,
        manufacturer TEXT NOT NULL,
        package TEXT,
        value TEXT,
        description TEXT,
        datasheet TEXT,
        manufacturer_link TEXT,
        kicad_symbol TEXT,
        kicad_footprint TEXT,
        altium_symbol TEXT,
        altium_footprint TEXT,
        lifecycle_status TEXT DEFAULT 'Active',
        rohs BOOLEAN DEFAULT TRUE,
        rohs_document_link TEXT,
        allow_substitution BOOLEAN DEFAULT TRUE,
        tracking BOOLEAN DEFAULT FALSE,
        standards_version TEXT DEFAULT 'v1.0',
        bom_comment TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        created_by TEXT,
        sim_model_type TEXT,
        sim_device TEXT,
        sim_pins TEXT,
        sim_model_file TEXT,
        sim_params TEXT
    ,
            function_type TEXT,
            resolution TEXT,
            channels INTEGER,
            sample_rate TEXT,
            interface TEXT,
            output_voltage TEXT,
            output_current TEXT,
            dropout_voltage TEXT,
            efficiency TEXT,
            propagation_delay TEXT,
            input_offset_voltage TEXT,
            reference_voltage TEXT,
            temp_coeff TEXT,
            supply_voltage_min TEXT,
            supply_voltage_max TEXT,
            supply_current TEXT,
            temp_operating TEXT,
            temp_storage TEXT,
            temp_junction_max TEXT
        );

-- Insert 12 components
BEGIN TRANSACTION;

INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('74LVC1G123', 'SN74LVC1G123', 'Texas Instruments', 'mssop-8', '74LVC1G123', 'Single Retrigerrable Monostabile Multivibrator, Low-Voltage CMOS', 'https://www.ti.com/lit/gpn/sn74lvc1g123', 'https://www.ti.com/product/SN74LVC1G123', 'terra_sym:74LVC1G123', 'Package_SO:MSOP-8_3x3mm_P0.65mm', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/TXII/TXII-E-A0013673131/TXII-E-A0013673131-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 1, '1.1', NULL, '2025-11-11T22:05:47.376863', '2025-11-11T22:05:47.376877', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/125C', '-65C/150C', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('74LVC1G123d', 'UNKNOWN', 'Generic', NULL, '74LVC1G123d', 'Single Retrigerrable Monostabile Multivibrator, Low-Voltage CMOS', 'http://www.ti.com/lit/ds/symlink/sn74lvc1g123.pdf', NULL, 'terra_sym:74LVC1G123d', NULL, NULL, NULL, 'Active', NULL, NULL, NULL, NULL, 'v1.0', NULL, '2025-11-11T22:05:47.377157', '2025-11-11T22:05:47.377163', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('FILTER TDK 25 MHz 12V SMT 0805 MEM2012F25R0T001', 'MEM2012F10R0T001 ', 'TDK', '0805', 'FILTER TDK 25 MHz 12V SMT 0805 MEM2012F25R0T001', 'EMI Filter, LP, 25 MHz, 12V', 'https://product.tdk.com/en/system/files?file=dam/doc/product/emc/emc/3tf/catalog/3tf_commercial_signal_mem2012f_en.pdf', 'https://product.tdk.com/en/search/emc/emc/3tf/info?part_no=MEM2012F25R0T001', 'terra_sym:FILTER TDK 25 MHz 12V SMT 0805 MEM2012F25R0T001', 'Isopoint:MEM2012F', NULL, NULL, 'Active', 1, 'https://product.tdk.com/system/files/dam/doc/product/emc/emc/beads/rohs/3tfrohs_mem_en.pdf', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.379658', '2025-11-11T22:05:47.379661', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', 'If applicable', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC Infineon BTS5030-1EJA MOSFET high-side switch 30 mOhm 5A 28V DSO-8', 'BTS5030-1EJA', 'Infineon', 'DSO-8-EP', 'BTS5030', 'Smart High-Side Power Switch, PROFET, Single, 30mOhm, 5A, 28V, DSO-8', 'https://www.infineon.com/dgdl/Infineon-BTS5030-1EJA-DS-v02_20-EN.pdf?fileId=5546d46259d9a4bf015a84f3e686758a', 'https://www.infineon.com/cms/en/product/power/smart-power-switches/high-side-switches/profet-plus-12v-automotive-smart-high-side-switch/bts5030-1eja/', 'terra_sym:IC Infineon BTS5030-1EJA MOSFET high-side switch 30 mOhm 5A 28V DSO-8', 'Package_SO:Infineon_PG-DSO-8-43', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/INFN/INFN-E-A0005477335/INFN-E-A0005477335-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.379958', '2025-11-11T22:05:47.379960', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/150C', '-55C/150C', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC LTC2851IMS8', 'LTC2851IMS8', 'Analog Devices', 'MSOP-8', 'LTC2851', 'RS232 transceiver 1 channel, 3v', 'https://www.analog.com/media/en/technical-documentation/data-sheets/285012fe.pdf', 'https://www.analog.com/en/products/ltc2851.html', 'terra_sym:IC LTC2851IMS8', 'Package_SO:MSOP-8_3x3mm_P0.65mm', NULL, NULL, 'Active', 1, 'https://www.mouser.com/catalog/additional/ADI_5584_RoHS_Certificate.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379995', '2025-11-11T22:05:47.379997', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40/+85C', '-65/+150C', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC SMBus level shifter 1v - 5v SOIC-8', 'PCA9306D', 'NXP', 'soic-8', 'PCA9306', 'SMBus level shifter, 1V - 5V', 'https://www.nxp.com/docs/en/data-sheet/PCA9306.pdf', 'https://www.nxp.com/part/PCA9306D', 'terra_sym:IC SMBus level shifter 1v - 5v SOIC-8', 'nema:Texas_DCT0008A_SSOP-8_2.95x2.8mm_P0.65mm', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/PHGL/PHGL-E-A0026066855/PHGL-E-A0026066855-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.380166', '2025-11-11T22:05:47.380168', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/105C', '-65C/150C', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC SMBus level shifter 1v - 5v SSOP-8', 'PCA9306DCT', 'Texas Instruments', 'ssop-8', 'PCA9306', 'TI PCA9306DCT SMBus level shifter, 1V - 5V', 'https://www.ti.com/lit/gpn/pca9306', 'https://www.ti.com/product/PCA9306?keyMatch=PCA9306', 'terra_sym:IC SMBus level shifter 1v - 5v SSOP-8', 'nema:Texas_DCT0008A_SSOP-8_2.95x2.8mm_P0.65mm', NULL, NULL, 'Active', 1, 'https://www.ti.com/lit/cr/szzq088r/szzq088r.pdf?ts=1759503142967', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.380204', '2025-11-11T22:05:47.380206', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/105C', '-65C/150C', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('INA180A2', 'INA180A2', 'Texas Instruments', 'SOT-23-5', 'INA180A2', '(type) Value,  params, pkg', 'http://www.ti.com/lit/ds/symlink/ina180.pdf', 'https://www.ti.com/product/INA180', 'terra_sym:INA180A2', 'Package_TO_SOT_SMD:SOT-23-5', NULL, NULL, 'Active', 1, 'RoHs Link', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.380601', '2025-11-11T22:05:47.380603', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/125C', 'If applicable', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('OPTO Optrex OPB733TR reflective optical sensor SMT', 'OPB733TR', 'Optrex', 'SMT', 'OPB733', 'OPTO TT/Optex OPB733 reflective sensor SMT', 'https://www.ttelectronics.com/TTElectronics/media/ProductFiles/Datasheet/OPB733.pdf', 'https://www.ttelectronics.com/Products/Sensors/Optoelectronics/Reflective-Sensors/OPB733TR', 'terra_sym:OPTO Optrex OPB733TR reflective optical sensor SMT', 'nema:OPB733TR', NULL, NULL, 'Active', 1, 'https://www.ttelectronics.com/TTElectronics/media/ProductFiles/Compliance/Lead-Free-and-RoHs-Compliance-for-Juarez-Site.pdf', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.381654', '2025-11-11T22:05:47.381657', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-25C/85C', '-25C/85C', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('SUPERVISOR APX823-44W5G-7', 'APX823-44W5G-7', 'Diodes Inc', 'SOT-23-5', 'SUPERVISOR APX823-44W5G-7', 'Watchdog timer, APXZ823-44W5G-7', 'https://www.diodes.com/assets/Datasheets/APX823_824_825A.pdf', 'https://www.diodes.com/part/view/APX823/', 'terra_sym:SUPERVISOR APX823-44W5G-7', 'Package_TO_SOT_SMD:SOT-23-5', NULL, NULL, 'Active', 1, 'https://www.diodes.com/assets/Quality-Reliability-Docs/Master_CofC.pdf', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.383046', '2025-11-11T22:05:47.383048', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', 'If applicable', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('SUPERVISOR CAT811LTBI-GT3', 'CAT811LTBI', 'OnSemi', 'SOT-143-4', 'SUPERVISOR CAT811LTBI-GT3', '(type) Value,  params, pkg', 'http://www.onsemi.com/pub/Collateral/CAT811-D.PDF', 'https://www.onsemi.com/products/power-management/voltage-references-supervisors/voltage-supervisors/cat811', 'terra_sym:SUPERVISOR CAT811LTBI-GT3', 'Package_TO_SOT_SMD:SOT-143', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/ONSM/ONSM-E-A0015053231/ONSM-E-A0015053231-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 1, '1.1', NULL, '2025-11-11T22:05:47.383084', '2025-11-11T22:05:47.383086', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', 'If applicable', NULL);
INSERT INTO ic_analog ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "function_type", "resolution", "channels", "sample_rate", "interface", "output_voltage", "output_current", "dropout_voltage", "efficiency", "propagation_delay", "input_offset_voltage", "reference_voltage", "temp_coeff", "supply_voltage_min", "supply_voltage_max", "supply_current", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('ULN2003A High current darlington array', 'UNL2003A', 'Texas Instruments', 'SOIC-16', 'ULN2003A High current darlington array', 'UNL2003A darlington array, high current', 'https://www.ti.com/lit/ds/symlink/uln2003a.pdf?ts=1666037723636&ref_url=https%253A%252F%252Fwww.google.com%252F', 'https://www.ti.com/product/ULN2003A', 'terra_sym:ULN2003A High current darlington array', 'Package_SO:SO-16_5.3x10.2mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/TXII/TXII-E-A0013673131/TXII-E-A0013673131-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 1, '1.1', NULL, '2025-11-11T22:05:47.383563', '2025-11-11T22:05:47.383565', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', 'if applicable', NULL);

COMMIT;
