#!/usr/bin/env python3
"""Harvest curated analog ICs from the abc4-spiro mainboard into native terra.

U2 = TI PCA9306DCT, a 2-bit bidirectional I2C/SMBus voltage-level translator
matched against the sparse cern_analog_interface table during conversion. Ported
here as a native part (the CERN PCA9306 rows are retired via the importer
denylist). Standard KiCad symbol (Interface:PCA9306) and footprint
(Package_SO:SSOP-8_2.95x2.8mm_P0.65mm) -- no asset migration needed.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ic_analog_generated_300_spiro_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "tags", "pin_count",
    "function_type", "channels", "resolution_bits", "interface",
    "supply_voltage_min", "supply_voltage_max",
]

PARTS = [
    {
        "unique_id": "Texas_Instruments-PCA9306DCT",
        "part_locator": "ic-analog-i2c-level-translator-2ch-ssop8",
        "mpn": "PCA9306DCT", "manufacturer": "Texas Instruments",
        "package": "SSOP-8", "value": "PCA9306",
        "description": "Texas Instruments PCA9306DCT 2-bit bidirectional I2C/SMBus voltage-level translator, SSOP-8",
        "datasheet": "${TERRA_EDA_LIB}/datasheets/ti/pca9306.pdf",
        "manufacturer_link": "https://www.ti.com/product/PCA9306",
        "kicad_symbol": "Interface:PCA9306",
        "kicad_footprint": "Package_SO:SSOP-8_2.95x2.8mm_P0.65mm",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "tags": "analog,level-translator,i2c", "pin_count": "8",
        "function_type": "I2C/SMBus level translator", "channels": 2,
        "resolution_bits": None, "interface": "I2C/SMBus",
        "supply_voltage_min": 1.0, "supply_voltage_max": 5.5,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - analog IC harvest from abc4-spiro mainboard",
        f"-- Curated analog ICs ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO ic_analog ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
