#!/usr/bin/env python3
"""Harvest curated BJTs from the abc4-spiro-cart cartridge board into native terra.

Deep electrical params (hFE, fT, Pd) are left NULL for the parametric harvest pass;
only the values carried by the curated symbol (Vceo, Ic) are populated.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("bjt_generated_310_cart_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "transistor_type", "channels", "v_ce_ds_max", "i_c_d_max",
    "power_dissipation", "hfe_typ", "rds_on", "vgs_th", "transition_freq",
    "temp_junction_max",
]

PARTS = [
    {
        "unique_id": "Diodes_Incorporated-MMBT3906",
        "part_locator": "bjt-pnp-40v-200ma-sot23",
        "mpn": "MMBT3906", "manufacturer": "Diodes Incorporated",
        "package": "SOT-23", "value": "MMBT3906",
        "description": "Diodes Inc MMBT3906 PNP general-purpose BJT, 40V 200mA, SOT-23",
        "datasheet": "https://www.diodes.com/assets/Datasheets/MMBT3906.pdf",
        "manufacturer_link": "https://www.diodes.com",
        "kicad_symbol": "Transistor_BJT:MMBT3906",
        "kicad_footprint": "Package_TO_SOT_SMD:SOT-23",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "keywords": "bjt,pnp", "pin_count": "3",
        "transistor_type": "pnp", "channels": 1,
        "v_ce_ds_max": "40V", "i_c_d_max": "200mA",
        "power_dissipation": None, "hfe_typ": None, "rds_on": None,
        "vgs_th": None, "transition_freq": None, "temp_junction_max": None,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - BJT harvest from abc4-spiro-cart cartridge board",
        f"-- Curated BJTs ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO bjt ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
