-- Terra EDA Library - ic_drivers Table
-- Number of components: 10
-- Sorted by: part_id
--
-- This file is auto-generated and suitable for git tracking.
-- Rows are sorted deterministically to ensure consistent diffs.
--

DROP TABLE IF EXISTS ic_drivers;

CREATE TABLE ic_drivers (
            
        part_id TEXT PRIMARY KEY,
        mpn TEXT NOT NULL,
        manufacturer TEXT NOT NULL,
        package TEXT,
        value TEXT,
        description TEXT,
        datasheet TEXT,
        manufacturer_link TEXT,
        kicad_symbol TEXT,
        kicad_footprint TEXT,
        altium_symbol TEXT,
        altium_footprint TEXT,
        lifecycle_status TEXT DEFAULT 'Active',
        rohs BOOLEAN DEFAULT TRUE,
        rohs_document_link TEXT,
        allow_substitution BOOLEAN DEFAULT TRUE,
        tracking BOOLEAN DEFAULT FALSE,
        standards_version TEXT DEFAULT 'v1.0',
        bom_comment TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        created_by TEXT,
        sim_model_type TEXT,
        sim_device TEXT,
        sim_pins TEXT,
        sim_model_file TEXT,
        sim_params TEXT
    ,
            driver_type TEXT,
            channels INTEGER,
            output_current TEXT,
            supply_voltage_min TEXT,
            supply_voltage_max TEXT,
            logic_voltage TEXT,
            output_type TEXT,
            switching_freq TEXT,
            control_interface TEXT,
            temp_operating TEXT,
            temp_storage TEXT,
            temp_junction_max TEXT
        );

-- Insert 10 components
BEGIN TRANSACTION;

INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC ISL834390 RS422 Tranceiver full duplex 3.3V soic-8', 'ISL83490IBZ', 'Renesas', 'soic-8', 'RS422', 'Full duplex RS-422 transciver, 2.5 Mbps, SOIC-8, 3.3V', 'https://www.renesas.com/en/document/dst/isl83483-isl83485-isl83488-isl83490-isl83491-datasheet', 'https://www.renesas.com/en/products/isl83490?srsltid=AfmBOorrhojJuPyDWNYh6-rDmOQmnBg03ja1MLg9s8OvA6xcdYZLD9Zv', 'terra_sym:IC ISL834390 RS422 Tranceiver full duplex 3.3V soic-8', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/RNCC/RNCC-E-A0024639703/RNCC-E-A0024639703-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379801', '2025-11-11T22:05:47.379803', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC ISL834390 RS422 Tranceiver full duplex 3.3V soic-8_flipped', 'ISL83490IBZ', 'Renesas', 'soic-8', 'RS422', 'Full duplex RS-422 transciver, 2.5 Mbps, SOIC-8, 3.3V', 'https://www.renesas.com/en/document/dst/isl83483-isl83485-isl83488-isl83490-isl83491-datasheet', 'https://www.renesas.com/en/products/isl83490?srsltid=AfmBOorrhojJuPyDWNYh6-rDmOQmnBg03ja1MLg9s8OvA6xcdYZLD9Zv', 'terra_sym:IC ISL834390 RS422 Tranceiver full duplex 3.3V soic-8_flipped', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/RNCC/RNCC-E-A0024639703/RNCC-E-A0024639703-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379915', '2025-11-11T22:05:47.379917', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8', 'MAX3488EESA+', 'Analog Devices', 'soic-8', 'RS422', 'Full duplex RS-422 transceiver, 250 kbps, SOIC-8, 3.3V', 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX3483E-MAX3491E.pdf', 'https://www.analog.com/en/products/max3488e.html', 'terra_sym:IC MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://www.mouser.com/catalog/additional/Maxim_6688_RoHS_Certificate.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.380032', '2025-11-11T22:05:47.380033', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8 flipped', 'MAX3488EESA+', 'Analog Devices', 'soic-8', 'RS422', 'Full duplex RS-422 transceiver, 250 kbps, SOIC-8, 3.3V', 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX3483E-MAX3491E.pdf', 'https://www.analog.com/en/products/max3488e.html', 'terra_sym:IC MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8 flipped', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://www.mouser.com/catalog/additional/Maxim_6688_RoHS_Certificate.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.380070', '2025-11-11T22:05:47.380072', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/85C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC MaxLinear SP490E RS422 Tranceiver full duplex 5V soic-8', 'SP490ECN-L', 'MaxLinear', 'soic-8', 'RS422', 'Full duplex RS-422 transciver, 2.5 Mbps, SOIC-8', 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX1487E-MAX491E.pdf', 'https://www.maxlinear.com/product/interface/serial-transceivers/rs485-422/sp490e', 'terra_sym:IC MaxLinear SP490E RS422 Tranceiver full duplex 5V soic-8', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://www.maxlinear.com/pdf/downloadquality?basePartNumber=SP490E&partNumber=SP490ECN-L_TR', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.380126', '2025-11-11T22:05:47.380128', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0C/70C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC TI ISO1412BDW Full Duplex isolated RS422 driver', 'ISO1412BDW', 'Texas Instruments', 'SOIC (DW)', 'IC TI ISO1412BDW Full Duplex isolated RS422 driver', 'Full Duplex, isolated RS 422 Driver, 500 kbps, SMT', 'https://www.ti.com/product/ISO1412/part-details/ISO1412BDW', 'https://www.ti.com/product/ISO1412/part-details/ISO1412BDW', 'terra_sym:IC TI ISO1412BDW Full Duplex isolated RS422 driver', 'Package_SO:SOIC-16W_7.5x10.3mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://www.ti.com/lit/cr/sszqqi4/sszqqi4.pdf?ts=1698698947760&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FISO1412', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.380289', '2025-11-11T22:05:47.380304', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40/+125C', '-65/+150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('IC TI ISO1412W Full Duplex isolated RS422 driver', 'ISOW1412', 'Texas Instruments', 'SOIC (DW)', 'IC TI ISO1412W Full Duplex isolated RS422 driver', 'Full Duplex, isolated RS 422 Driver, 500 kbps, SMT', 'https://www.ti.com/lit/ds/symlink/isow1432.pdf', 'https://www.ti.com/product/ISOW1412', 'terra_sym:IC TI ISO1412W Full Duplex isolated RS422 driver', 'Package_SO:SOIC-20W_7.5x12.8mm_P1.27mm', NULL, NULL, 'Active', 1, 'https://www.ti.com/lit/cr/sszqqi4/sszqqi4.pdf?ts=1698698947760&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FISO1412', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.380339', '2025-11-11T22:05:47.380341', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40/+125C', '-65/+150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('LED DRIVER Diodes Inc AL8843Q', 'AL8843Q', 'Diodes, Inc', 'SO-8EP', 'LED DRIVER Diodes Inc AL8843Q', 'LED Driver 40V 3A Step-down', 'https://www.diodes.com/assets/Datasheets/AL8843Q.pdf', 'https://www.diodes.com/part/view/AL8843Q/', 'terra_sym:LED DRIVER Diodes Inc AL8843Q', 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/DIOD/DIOD-E-A0004063887/DIOD-E-A0004063887-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 1, '1.1', NULL, '2025-11-11T22:05:47.381044', '2025-11-11T22:05:47.381046', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/150C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('LED DRIVER Lumissil IS32LT3954', 'IS32LT3954', 'Diodes, Inc', 'SO-8EP', 'LED DRIVER Lumissil IS32LT3954', 'LED Driver 40V 3A Step-down', 'http://www.lumissil.com/assets/pdf/core/IS32LT3954_DS.pdf', 'http://www.lumissil.com/home', 'terra_sym:LED DRIVER Lumissil IS32LT3954', 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/ISSI/ISSI-E-A0014960646/ISSI-E-A0014960646-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 1, '1.1', NULL, '2025-11-11T22:05:47.381090', '2025-11-11T22:05:47.381093', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/125C', '-65C/150C', NULL);
INSERT INTO ic_drivers ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "driver_type", "channels", "output_current", "supply_voltage_min", "supply_voltage_max", "logic_voltage", "output_type", "switching_freq", "control_interface", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('LED DRIVER Texas Instruments LM3410XMY/NOPB', 'LM3410XMY/NOPB', 'Texas Instruments', 'MSOP Powerpad 8', 'LED DRIVER Texas Instruments LM3410XMY{slash}NOPB', 'LED Driver 24V 2.8A constant current w/internal compensation', 'https://www.ti.com/lit/gpn/LM3410', 'https://www.ti.com/store/ti/en/p/product/?p=LM3410XMY/NOPB', 'terra_sym:LED DRIVER Texas Instruments LM3410XMY/NOPB', 'Isopoint:LM3410XMY&slash_NOPB', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/TXII/TXII-E-A0013673131/TXII-E-A0013673131-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 1, '1.1', NULL, '2025-11-11T22:05:47.381135', '2025-11-11T22:05:47.381137', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40C/125C', NULL, NULL);

COMMIT;
