-- KiCad Symbol Library SQL Script
-- Generated from: terra_sym.kicad_sym
-- Number of symbols: 14
--
-- To create the database, run:
--   sqlite3 output.db < ic_drivers_1_migrated.sql
--

-- Create symbols table
CREATE TABLE IF NOT EXISTS ic_drivers (
  "unique_id" TEXT PRIMARY KEY,
  "part_locator" TEXT,
  "allow_substitution" TEXT,
  "bom_comment" TEXT,
  "class" TEXT,
  "component_type" TEXT,
  "component_value" TEXT,
  "current_rating" TEXT,
  "datasheet" TEXT,
  "description" TEXT,
  "kicad_footprint" TEXT,
  "manufacturer" TEXT,
  "manufacturer_link" TEXT,
  "mpn" TEXT,
  "composition" TEXT,
  "number_of_pins" TEXT,
  "package" TEXT,
  "power_rating" TEXT,
  "reference" TEXT,
  "rohs" TEXT,
  "rohs_document_link" TEXT,
  "sim_device" TEXT,
  "sim_library" TEXT,
  "sim_pins" TEXT,
  "sim_type" TEXT,
  "standards_version" TEXT,
  "kicad_symbol" TEXT,
  "temp_operating" TEXT,
  "temp_soldering" TEXT,
  "temp_storage" TEXT,
  "temp_coeff" TEXT,
  "tolerance" TEXT,
  "tracking" TEXT,
  "value" TEXT,
  "variant" TEXT,
  "altium_footprint" TEXT,
  "altium_symbol" TEXT,
  "source" TEXT,
  "dump_priority" INTEGER
);

-- Insert symbols
BEGIN TRANSACTION;

INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('ON Semi- SZNUD3124DMT1G', 'IC_DRIVER DUAL FET DRIVER SZNUD3124DMT1G', 'No', NULL, 'MOSFET', 'MOSFET', 'Comp. Value', '150 mA', 'https://www.onsemi.com/download/data-sheet/pdf/nud3124-d.pdf', 'Dual MOSFET Relay driver SMT', 'terra_sym:SC-74-6_1.5x2.9mm_P0.95mm', 'ON Semi', 'https://www.onsemi.com/products/motor-control/motor-drivers/load-drivers-relay-drivers/nud3124', ' SZNUD3124DMT1G', 'n/a', '6', NULL, NULL, 'Q', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/ONSM/ONSM-E-A0015053231/ONSM-E-A0015053231-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER DUAL FET DRIVER SZNUD3124DMT1G', '-40C/125C', 'If applicable', 'If applicable', 'n/a', 'If applicable', 'No', 'FET DRIVER DUAL SZNUD3124DMT1G', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Renesas-ISL83490IBZ', 'IC_DRIVER ISL834390 RS422 Tranceiver full duplex 3.3V soic-8', 'Yes', NULL, 'n/a', 'IC Driver', 'RS-422', NULL, 'https://www.renesas.com/en/document/dst/isl83483-isl83485-isl83488-isl83490-isl83491-datasheet', 'Full duplex RS-422 transciver, 2.5 Mbps, SOIC-8, 3.3V', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'Renesas', 'https://www.renesas.com/en/products/isl83490?srsltid=AfmBOorrhojJuPyDWNYh6-rDmOQmnBg03ja1MLg9s8OvA6xcdYZLD9Zv', 'ISL83490IBZ', 'n/a', '8', 'soic-8', 'n/a', 'U', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/RNCC/RNCC-E-A0024639703/RNCC-E-A0024639703-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER ISL834390 RS422 Tranceiver full duplex 3.3V soic-8', '-40C/85C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'RS422', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Renesas-ISL83490IBZ-flipped', 'IC_DRIVER ISL834390 RS422 Tranceiver full duplex 3.3V soic-8_flipped', 'Yes', NULL, 'n/a', 'IC Driver', 'RS-422', NULL, 'https://www.renesas.com/en/document/dst/isl83483-isl83485-isl83488-isl83490-isl83491-datasheet', 'Full duplex RS-422 transciver, 2.5 Mbps, SOIC-8, 3.3V', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'Renesas', 'https://www.renesas.com/en/products/isl83490?srsltid=AfmBOorrhojJuPyDWNYh6-rDmOQmnBg03ja1MLg9s8OvA6xcdYZLD9Zv', 'ISL83490IBZ', 'n/a', '8', 'soic-8', 'n/a', 'U', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/RNCC/RNCC-E-A0024639703/RNCC-E-A0024639703-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER ISL834390 RS422 Tranceiver full duplex 3.3V soic-8_flipped', '-40C/85C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'RS422', 'flipped', NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Analog Devices-LTC2851IMS8', 'IC_DRIVER LTC2851IMS8', 'Yes', NULL, 'na', 'Interface IC', 'LTC2851', NULL, 'https://www.analog.com/media/en/technical-documentation/data-sheets/285012fe.pdf', 'RS232 transceiver 1 channel, 3v', 'Package_SO:MSOP-8_3x3mm_P0.65mm', 'Analog Devices', 'https://www.analog.com/en/products/ltc2851.html', 'LTC2851IMS8', 'na', '8', 'MSOP-8', 'na', 'U', 'Yes', 'https://www.mouser.com/catalog/additional/ADI_5584_RoHS_Certificate.pdf', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER LTC2851IMS8', '-40/+85C', '300C, 10sec', '-65/+150C', 'na', 'If applicable', 'No', 'LTC2851', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Analog Devices-MAX3488EESA+', 'IC_DRIVER MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8', 'Yes', NULL, 'n/a', 'IC Driver', 'RS-422', NULL, 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX3483E-MAX3491E.pdf', 'Full duplex RS-422 transceiver, 250 kbps, SOIC-8, 3.3V', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'Analog Devices', 'https://www.analog.com/en/products/max3488e.html', 'MAX3488EESA+', 'n/a', '8', 'soic-8', 'n/a', 'U', 'Yes', 'https://www.mouser.com/catalog/additional/Maxim_6688_RoHS_Certificate.pdf', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8', '-40C/85C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'RS422', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Analog Devices-MAX3488EESA+-flipped', 'IC_DRIVER MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8 flipped', 'Yes', NULL, 'n/a', 'IC Driver', 'RS-422', NULL, 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX3483E-MAX3491E.pdf', 'Full duplex RS-422 transceiver, 250 kbps, SOIC-8, 3.3V', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'Analog Devices', 'https://www.analog.com/en/products/max3488e.html', 'MAX3488EESA+', 'n/a', '8', 'soic-8', 'n/a', 'U', 'Yes', 'https://www.mouser.com/catalog/additional/Maxim_6688_RoHS_Certificate.pdf', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER MAX3488E RS422 Tranceiver full duplex 3.3V 15kv ESD soic-8 flipped', '-40C/85C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'RS422', 'flipped', NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('MaxLinear-SP490ECN-L', 'IC_DRIVER MaxLinear SP490E RS422 Tranceiver full duplex 5V soic-8', 'Yes', NULL, 'n/a', 'IC Driver', 'SP490E', NULL, 'https://www.analog.com/media/en/technical-documentation/data-sheets/MAX1487E-MAX491E.pdf', 'Full duplex RS-422 transciver, 2.5 Mbps, SOIC-8', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'MaxLinear', 'https://www.maxlinear.com/product/interface/serial-transceivers/rs485-422/sp490e', 'SP490ECN-L', 'n/a', '8', 'soic-8', 'n/a', 'U', 'Yes', 'https://www.maxlinear.com/pdf/downloadquality?basePartNumber=SP490E&partNumber=SP490ECN-L_TR', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER MaxLinear SP490E RS422 Tranceiver full duplex 5V soic-8', '0C/70C', 'If applicable', '-65C/150C', 'n/a', 'If applicable', 'No', 'RS422', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('NXP-PCA9306D', 'IC_DRIVER SMBus level shifter 1v - 5v SOIC-8', 'No', NULL, 'n/a', 'Level Shifter', 'PCA9306', NULL, 'https://www.nxp.com/docs/en/data-sheet/PCA9306.pdf', 'SMBus level shifter, 1V - 5V', 'terra_sym:Texas_DCT0008A_SSOP-8_2.95x2.8mm_P0.65mm', 'NXP', 'https://www.nxp.com/part/PCA9306D', 'PCA9306D', 'n/a', '8', 'soic-8', 'n/a', 'U', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/PHGL/PHGL-E-A0026066855/PHGL-E-A0026066855-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER SMBus level shifter 1v - 5v SOIC-8', '-40C/105C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'PCA9306', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Texas Instruments-PCA9306DCT', 'IC_DRIVER SMBus level shifter 1v - 5v SSOP-8', 'No', NULL, 'n/a', 'Level Shifter', 'PCA9306', NULL, 'https://www.ti.com/lit/gpn/pca9306', 'TI PCA9306DCT SMBus level shifter, 1V - 5V', 'terra_sym:Texas_DCT0008A_SSOP-8_2.95x2.8mm_P0.65mm', 'Texas Instruments', 'https://www.ti.com/product/PCA9306?keyMatch=PCA9306', 'PCA9306DCT', 'n/a', '8', 'ssop-8', 'n/a', 'U', 'Yes', 'https://www.ti.com/lit/cr/szzq088r/szzq088r.pdf?ts=1759503142967', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER SMBus level shifter 1v - 5v SSOP-8', '-40C/105C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'PCA9306', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Texas Instruments-ISO1412BDW', 'IC_DRIVER TI ISO1412BDW Full Duplex isolated RS422 driver', 'Yes', NULL, NULL, 'IC', 'ISO1412BDW', NULL, 'https://www.ti.com/product/ISO1412/part-details/ISO1412BDW', 'Full Duplex, isolated RS 422 Driver, 500 kbps, SMT', 'Package_SO:SOIC-16W_7.5x10.3mm_P1.27mm', 'Texas Instruments', 'https://www.ti.com/product/ISO1412/part-details/ISO1412BDW', 'ISO1412BDW', NULL, '16', 'SOIC (DW)', NULL, 'U', 'Yes', 'https://www.ti.com/lit/cr/sszqqi4/sszqqi4.pdf?ts=1698698947760&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FISO1412', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER TI ISO1412BDW Full Duplex isolated RS422 driver', '-40/+125C', NULL, '-65/+150C', NULL, 'na', 'No', 'IC TI ISO1412BDW Full Duplex isolated RS422 driver', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Texas Instruments-ISOW1412', 'IC_DRIVER TI ISO1412W Full Duplex isolated RS422 driver', 'Yes', NULL, NULL, 'IC', 'ISOW1412', NULL, 'https://www.ti.com/lit/ds/symlink/isow1432.pdf', 'Full Duplex, isolated RS 422 Driver, 500 kbps, SMT', 'Package_SO:SOIC-20W_7.5x12.8mm_P1.27mm', 'Texas Instruments', 'https://www.ti.com/product/ISOW1412', 'ISOW1412', NULL, '16', 'SOIC (DW)', NULL, 'U', 'Yes', 'https://www.ti.com/lit/cr/sszqqi4/sszqqi4.pdf?ts=1698698947760&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FISO1412', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER TI ISO1412W Full Duplex isolated RS422 driver', '-40/+125C', NULL, '-65/+150C', NULL, 'na', 'No', 'IC TI ISO1412W Full Duplex isolated RS422 driver', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Texas Instrument-TXU0104PWR', 'IC_DRIVER TXU0104 4-bit level shifter 1.8v - 5v TSSOP-14', 'No', NULL, 'n/a', 'Level Shifter', 'TXU0104', NULL, 'https://www.ti.com/lit/gpn/TXU0104', '4-bit Level Shifting Buffer 1.8V <> 5V', 'Package_SO:TSSOP-14_4.4x5mm_P0.65mm', 'Texas Instrument', 'https://www.ti.com/lit/ds/symlink/sn74lv1t125.pdf?ts=1758919582957', 'TXU0104PWR', 'n/a', '14', 'TSSOP-14', 'n/a', 'U', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/TXII/TXII-E-A0021022709/TXII-E-A0021022709-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER TXU0104 4-bit level shifter 1.8v - 5v TSSOP-14', '-40C/125C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'TXU0104', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('Texas Instruments-UNL2003A', 'IC_DRIVER ULN2003A High current darlington array', 'Yes', NULL, 'darlington', 'IC', 'ULN2003A', NULL, 'https://www.ti.com/lit/ds/symlink/uln2003a.pdf?ts=1666037723636&ref_url=https%253A%252F%252Fwww.google.com%252F', 'UNL2003A darlington array, high current', 'Package_SO:SO-16_5.3x10.2mm_P1.27mm', 'Texas Instruments', 'https://www.ti.com/product/ULN2003A', 'UNL2003A', 'n/a', '16', 'SOIC-16', '2.5A', 'IC', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/TXII/TXII-E-A0013673131/TXII-E-A0013673131-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER ULN2003A High current darlington array', '-40C/85C', 'If applicable', 'if applicable', 'n/a', 'n/a', 'Yes', 'ULN2003A High current darlington array', NULL, NULL, NULL, 'terra_sym', 100);
INSERT INTO ic_drivers ("unique_id", "part_locator", "allow_substitution", "bom_comment", "class", "component_type", "component_value", "current_rating", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "number_of_pins", "package", "power_rating", "reference", "rohs", "rohs_document_link", "sim_device", "sim_library", "sim_pins", "sim_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "variant", "altium_footprint", "altium_symbol", "source", "dump_priority") VALUES ('NXP-SN74LV1T125DBV', 'IC_DRIVER level shifter 1.8v - 5v SOT-23-5', 'No', NULL, 'n/a', 'Level Shifter', 'SN74LV1T125', NULL, 'https://www.ti.com/lit/ds/symlink/sn74lv1t125.pdf?ts=1758962409857', 'Single Level Shifting Buffer 1.8V <> 5V', 'Package_TO_SOT_SMD:SOT-23-5', 'NXP', 'https://www.ti.com/lit/ds/symlink/sn74lv1t125.pdf?ts=1758919582957', 'SN74LV1T125DBV', 'n/a', '5', 'SOT 23-5', 'n/a', 'U', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/TXII/TXII-E-A0026917336/TXII-E-A0026917336-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', NULL, NULL, NULL, NULL, '1.1', 'terra_sym:IC_DRIVER level shifter 1.8v - 5v SOT-23-5', '-40C/125C', NULL, '-65C/150C', 'n/a', 'n/a', 'No', 'SN74LV1T125DBV', NULL, NULL, NULL, 'terra_sym', 100);

COMMIT;
