-- KiCad Symbol Library SQL Script
-- Generated from: terra_sym.kicad_sym
-- Number of symbols: 9
--
-- To create the database, run:
--   sqlite3 output.db < diodes_1_migrated.sql
--

-- Create symbols table

BEGIN TRANSACTION;

INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "pin_count", "temp_operating_min", "temp_operating_max", "power_rating") VALUES ('Diodes, Inc.-MMBD914-7-F', 'DIODE MMBD914 small signal switching diode SMT SOT23', 'MMBD914-7-F', 'Diodes, Inc.', 'SOT23', 'MMBD914', 'DIODE SMT/TH 1n914/mmbd914 generic switching', 'https://www.diodes.com/assets/Datasheets/BAS16_MMBD4148_MMBD914.pdf', 'https://www.diodes.com/part/view/MMBD914', 'terra_sym:DIODE MMBD914 small signal switching diode SMT SOT23', 'Package_TO_SOT_SMD:SOT-23', 'Yes', 'https://www.diodes.com/assets/Quality-Reliability-Docs/Master_CofC.pdf', 'Yes', 'No', '1.1', 'terra_sym', '100', '3', '-65', '150', '350 mW / 200 mA');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "pin_count", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "current_rating", "diode_type", "voltage_rating", "forward_voltage", "forward_current") VALUES ('Nexperia-PNE20020ER', 'DIODE Nexperia PNE20020ERX 200V 2.8A Fast Recovery SOD123', 'PNE20020ER', 'Nexperia', 'SOD123W', '200V 2A', '200V hyperfast recovery rectifier, Vf 0.98V @ 2A, Iav 2A, trr 25ns', '${TERRA_EDA_LIB}/datasheets/nexperia/pne20020er.pdf', 'https://www.nexperia.com/products/diodes/recovery-rectifiers/PNE20020ER.html', 'terra_sym:DIODE Nexperia PNE20020ERX 200V 2.8A Fast Recovery SOD123', 'terra_sym:Nexperia SOD-123W', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/RECT/RECT-E-A0007327236/RECT-E-A0007327236-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'Yes', 'No', '1.1', 'terra_sym', '100', '2', '-55', '175', '-65', '175', '2A', 'rectifier', '200V', '0.98V', '2.8A');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "diode_type") VALUES ('OnSemi-MBR0530T1G', 'DIODE OnSemi Schottky 30V 0.5A SOD-123 MBR0530', 'MBR0530T1G', 'OnSemi', 'SOD-123', 'DIODE OnSemi Schottky 30V 0.5A SOD-123 MBR0530', '30V 0.5A Schottky Power Rectifier Diode', 'https://www.onsemi.com/pdf/datasheet/mbr0530t1-d.pdf', 'https://www.onsemi.com/products/discrete-power-modules/schottky-diodes-schottky-rectifiers/mbr0530', 'terra_sym:DIODE OnSemi Schottky 30V 0.5A SOD-123 MBR0530', 'Diode_SMD:D_SOD-123', 'Yes', 'https://www.mouser.com/catalog/additional/On_Semiconductor_5121_RoHS_Certificate.pdf', 'Yes', 'No', '1.1', 'terra_sym', '100', '-65', '125', '-65', '150', 'schottky');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "pin_count", "temp_storage_min", "temp_storage_max", "current_rating") VALUES ('ROHM-RFN10TB4SNZC9', 'DIODE ROHM RFN10TB4SNZC9 430V 10A', 'RFN10TB4SNZC9', 'ROHM', 'TO-220FN-2', '_TEMPLATE MANUF [VALUE] [PARAMS] [PKG] [MPN]', 'General Purpose DIode, fast recovery, Vf 430V, Iav 10A', 'RFN10TB4SNZC9', 'https://www.rohm.com/products/diodes/fast-recovery-diodes/standard/rfn10tb4snz-product', 'terra_sym:DIODE ROHM RFN10TB4SNZC9 430V 10A', 'Package_TO_SOT_THT:TO-220-2_Vertical', 'Yes', 'https://fscdn.rohm.com/en/techdata_basic/diode/rohs-elv/ROHS_ELV_Diode-e.pdf', 'Yes', 'No', '1.1', 'terra_sym', '100', '2', '-55', '150', '10 Avg');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "pin_count", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "current_rating") VALUES ('Rectron-FR204-B', 'DIODE Rectron  FR204-B 400V 2A Fast Recovery', 'FR204-B', 'Rectron', 'DO-15', '400V 2A', 'General Purpose DIode, fast recovery, Vf 400V, Iav 2A', 'https://www.rectron.com/public/product_datasheets/fr201-fr207.pdf', 'https://www.rectron.com/category/4/50', 'terra_sym:DIODE Rectron  FR204-B 400V 2A Fast Recovery', 'Diode_THT:D_DO-15_P10.16mm_Horizontal', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/RECT/RECT-E-A0007327236/RECT-E-A0007327236-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'Yes', 'No', '1.1', 'terra_sym', '100', '2', '-55', '150', '-55', '150', '2A');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "diode_type") VALUES ('Vishay-VSSAF510-M3/H', 'DIODE Vishay VSSAF510  Schottky 5A', 'VSSAF510-M3/H', 'Vishay', 'SMA (DO-214AC)', 'VSSAF510', '100V 5A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/87610/vssaf510.pdf', 'https://www.vishay.com/en/product/87610/', 'terra_sym:DIODE Vishay VSSAF510  Schottky 5A', 'terra_sym:Vishay_SlimSMA_D_DO-221AC', 'Yes', 'https://www.vishay.com/en/how/leadfree/#summary', 'Yes', 'No', '1.1', 'terra_sym', '100', '-65', '150', '-65', '150', 'schottky');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "diode_type") VALUES ('Vishay-VSSAF512', 'DIODE Vishay VSSAF512  Schottky 5A', 'VSSAF512', 'Vishay', 'SMA (DO-214AC)', 'VSSAF512', '120V 5A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/87611/vssaf512.pdf', 'https://www.vishay.com/en/product/87611/', 'terra_sym:DIODE Vishay VSSAF512  Schottky 5A', 'terra_sym:Vishay_SlimSMA_D_DO-221AC', 'Yes', 'https://www.vishay.com/en/how/leadfree/#summary', 'Yes', 'No', '1.1', 'terra_sym', '100', '-65', '150', '-65', '150', 'schottky');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "diode_type") VALUES ('Vishay-VSSB410S', 'DIODE Vishay VSSB410S Schottky 4A', 'VSSB410S', 'Vishay', 'SMB (DO-214AA)', 'VSSB410S', '100V 4A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/89140/vssb410s-e3.pdf', 'https://www.vishay.com/en/product/89140/', 'terra_sym:DIODE Vishay VSSB410S Schottky 4A', 'Diode_SMD:D_SMB', 'Yes', 'https://www.vishay.com/en/how/leadfree/#summary', 'Yes', 'No', '1.1', 'terra_sym', '100', '-65', '150', '-65', '150', 'schottky');
INSERT INTO diodes ("unique_id", "part_locator", "mpn", "manufacturer", "value", "description", "datasheet", "kicad_symbol", "kicad_footprint", "source", "dump_priority") VALUES ('Unknown-UNKNOWN', 'DIODE_ARRAY PESD3V3L4UW', 'UNKNOWN', 'Unknown', 'PESD3V3L4UW', 'Low capacitance unidirectional quadruple ESD protection diode array, 3.3V, Common Anode, SOT-665', 'https://assets.nexperia.com/documents/data-sheet/PESDXL4UF_G_W.pdf', 'terra_sym:DIODE_ARRAY PESD3V3L4UW', 'Package_TO_SOT_SMD:SOT-665', 'terra_sym', '100');

COMMIT;
