-- Terra EDA Library - diodes Table
-- Number of components: 23
-- Sorted by: part_id
--
-- This file is auto-generated and suitable for git tracking.
-- Rows are sorted deterministically to ensure consistent diffs.
--

DROP TABLE IF EXISTS diodes;

CREATE TABLE diodes (
            
        part_id TEXT PRIMARY KEY,
        mpn TEXT NOT NULL,
        manufacturer TEXT NOT NULL,
        package TEXT,
        value TEXT,
        description TEXT,
        datasheet TEXT,
        manufacturer_link TEXT,
        kicad_symbol TEXT,
        kicad_footprint TEXT,
        altium_symbol TEXT,
        altium_footprint TEXT,
        lifecycle_status TEXT DEFAULT 'Active',
        rohs BOOLEAN DEFAULT TRUE,
        rohs_document_link TEXT,
        allow_substitution BOOLEAN DEFAULT TRUE,
        tracking BOOLEAN DEFAULT FALSE,
        standards_version TEXT DEFAULT 'v1.0',
        bom_comment TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        created_by TEXT,
        sim_model_type TEXT,
        sim_device TEXT,
        sim_pins TEXT,
        sim_model_file TEXT,
        sim_params TEXT
    ,
            diode_type TEXT,
            forward_voltage TEXT,
            forward_current TEXT,
            reverse_voltage TEXT,
            reverse_current TEXT,
            power_dissipation TEXT,
            recovery_time TEXT,
            capacitance TEXT,
            zener_voltage TEXT,
            clamping_voltage TEXT,
            temp_operating TEXT,
            temp_storage TEXT,
            temp_junction_max TEXT
        );

-- Insert 23 components
BEGIN TRANSACTION;

INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE MMBD914 small signal switching diode SMT SOT23', 'MMBD914-7-F', 'Diodes, Inc.', 'SOT23', 'MMBD914', 'DIODE SMT/TH 1n914/mmbd914 generic switching', 'https://www.diodes.com/assets/Datasheets/BAS16_MMBD4148_MMBD914.pdf', 'https://www.diodes.com/part/view/MMBD914', 'terra_sym:DIODE MMBD914 small signal switching diode SMT SOT23', 'Package_TO_SOT_SMD:SOT-23', NULL, NULL, 'Active', 1, 'https://www.diodes.com/assets/Quality-Reliability-Docs/Master_CofC.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379244', '2025-11-11T22:05:47.379246', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/150C', 'If applicable', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Nexperia PNE20020ERX 200V 2.8A Fast Recovery SOD123', 'PNE20020ER', 'Nexperia', 'SOD123W', '200V 2.8A', 'General Purpose DIode, fast recovery, Vf 400V, Iav 2A', 'https://assets.nexperia.com/documents/data-sheet/PNE20020ER.pdf', 'https://www.nexperia.com/products/diodes/recovery-rectifiers/PNE20020ER.html', 'terra_sym:DIODE Nexperia PNE20020ERX 200V 2.8A Fast Recovery SOD123', 'nema:Nexperia SOD-123W', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/RECT/RECT-E-A0007327236/RECT-E-A0007327236-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379275', '2025-11-11T22:05:47.379277', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/150C', '-55C/150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE OnSemi Schottky 30V 0.5A SOD-123 MBR0530', 'MBR0530T1G', 'OnSemi', 'SOD-123', 'DIODE OnSemi Schottky 30V 0.5A SOD-123 MBR0530', '30V 0.5A Schottky Power Rectifier Diode', 'https://www.onsemi.com/pdf/datasheet/mbr0530t1-d.pdf', 'https://www.onsemi.com/products/discrete-power-modules/schottky-diodes-schottky-rectifiers/mbr0530', 'terra_sym:DIODE OnSemi Schottky 30V 0.5A SOD-123 MBR0530', 'Diode_SMD:D_SOD-123', NULL, NULL, 'Active', 1, 'https://www.mouser.com/catalog/additional/On_Semiconductor_5121_RoHS_Certificate.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379303', '2025-11-11T22:05:47.379305', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/+125C', '-65C/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE ROHM RFN10TB4SNZC9 430V 10A', 'RFN10TB4SNZC9', 'ROHM', 'TO-220FN-2', '_TEMPLATE MANUF [VALUE] [PARAMS] [PKG] [MPN]', 'General Purpose DIode, fast recovery, Vf 430V, Iav 10A', 'RFN10TB4SNZC9', 'https://www.rohm.com/products/diodes/fast-recovery-diodes/standard/rfn10tb4snz-product', 'terra_sym:DIODE ROHM RFN10TB4SNZC9 430V 10A', 'Package_TO_SOT_THT:TO-220-2_Vertical', NULL, NULL, 'Active', 1, 'https://fscdn.rohm.com/en/techdata_basic/diode/rohs-elv/ROHS_ELV_Diode-e.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379331', '2025-11-11T22:05:47.379335', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '150C', '-55C/150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Rectron  FR204-B 400V 2A Fast Recovery', 'FR204-B', 'Rectron', 'DO-15', '400V 2A', 'General Purpose DIode, fast recovery, Vf 400V, Iav 2A', 'https://www.rectron.com/public/product_datasheets/fr201-fr207.pdf', 'https://www.rectron.com/category/4/50', 'terra_sym:DIODE Rectron  FR204-B 400V 2A Fast Recovery', 'Diode_THT:D_DO-15_P10.16mm_Horizontal', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/RECT/RECT-E-A0007327236/RECT-E-A0007327236-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379360', '2025-11-11T22:05:47.379362', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/150C', '-55C/150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Vishay   VSSAF512  Schottky 5A', 'VSSAF512', 'Vishay', 'SMA (DO-214AC)', 'DIODE Vishay   VSSAF512  Schottky 5A', '120V 5A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/87611/vssaf512.pdf', 'https://www.vishay.com/en/product/87611/', 'terra_sym:DIODE Vishay   VSSAF512  Schottky 5A', 'Diode_SMD:D_SMA', NULL, NULL, 'Active', 1, 'https://www.vishay.com/en/how/leadfree/#summary', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379387', '2025-11-11T22:05:47.379389', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/+150C', '-65C/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Vishay  VSSB410S Schottky 4A', ' VSSB410S', 'Vishay', 'SMB (DO-214AA)', 'DIODE Vishay  VSSB410S Schottky 4A', '100V 4A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/89140/vssb410s-e3.pdf', 'https://www.vishay.com/en/product/89140/', 'terra_sym:DIODE Vishay  VSSB410S Schottky 4A', 'Diode_SMD:D_SMB', NULL, NULL, 'Active', 1, 'https://www.vishay.com/en/how/leadfree/#summary', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379414', '2025-11-11T22:05:47.379415', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/+150C', '-65C/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Vishay VSSAF510  Schottky 5A', 'VSSAF510-M3/H', 'Vishay', 'SMA (DO-214AC)', 'VSSAF510', '100V 5A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/87610/vssaf510.pdf', 'https://www.vishay.com/en/product/87610/', 'terra_sym:DIODE Vishay VSSAF510  Schottky 5A', 'nema:Vishay_SlimSMA_D_DO-221AC', NULL, NULL, 'Active', 1, 'https://www.vishay.com/en/how/leadfree/#summary', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379446', '2025-11-11T22:05:47.379447', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/+150C', '-65C/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Vishay VSSAF512  Schottky 5A', 'VSSAF512', 'Vishay', 'SMA (DO-214AC)', 'VSSAF512', '120V 5A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/87611/vssaf512.pdf', 'https://www.vishay.com/en/product/87611/', 'terra_sym:DIODE Vishay VSSAF512  Schottky 5A', 'nema:Vishay_SlimSMA_D_DO-221AC', NULL, NULL, 'Active', 1, 'https://www.vishay.com/en/how/leadfree/#summary', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379472', '2025-11-11T22:05:47.379474', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/+150C', '-65C/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('DIODE Vishay VSSB410S Schottky 4A', ' VSSB410S', 'Vishay', 'SMB (DO-214AA)', 'VSSB410S', '100V 4A Schottky Power Rectifier Diode', 'https://www.vishay.com/docs/89140/vssb410s-e3.pdf', 'https://www.vishay.com/en/product/89140/', 'terra_sym:DIODE Vishay VSSB410S Schottky 4A', 'Diode_SMD:D_SMB', NULL, NULL, 'Active', 1, 'https://www.vishay.com/en/how/leadfree/#summary', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.379499', '2025-11-11T22:05:47.379501', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/+150C', '-65C/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('ESD_PESD3V3L4UW', 'PESD3V3L4UW', 'Nexperia', 'SOT-665', 'PESD3V3L4UW', 'Low capacitance unidirectional quadruple ESD protection diode array, 3.3V, Common Anode, SOT-665', 'https://assets.nexperia.com/documents/data-sheet/PESDXL4UF_G_W.pdf', 'https://www.nexperia.com/product/PESD3V3L4UW', 'terra_sym:PESD3V3L4UW', 'Package_TO_SOT_SMD:SOT-665', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/NEXP/NEXP-E-A0027395186/NEXP-E-A0027395186-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, 'v1.0', NULL, '2025-11-11T22:05:47.379147', '2025-11-11T22:05:47.379149', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/150C', '-65C/150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS Diotec 30kV, 1.8V, Unidirection, SMT', ' VESD03C1-02V-G3-08', 'Diotec', 'SOD-523', '30kV, 1.8V', 'TVS Diotec 30kV, 1.8V, Unidirection, SMT', 'https://diotec.com/request/datasheet/esd1v8wt.pdf', 'https://diotec.com/index.php/en/product/ESD1V8WT.html', 'terra_sym:TVS Diotec 30kV, 1.8V, Unidirection, SMT', 'nema:SOD-523', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.383264', '2025-11-11T22:05:47.383266', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/+150C', 'If applicable', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS Littlefuse SMF18A 18V 200W SOD-123-FL', 'SMF18A', 'Littlefuse', 'SOD-123FL', '18V 200W', 'TVS, 18V working, 20 Breakdown, 29.2V Clamping, 200W SOD123FL', 'https://www.littelfuse.com/media?resourcetype=datasheets&itemid=7eb8a5b6-bdd0-4561-8f19-0c3cc6f9b2af&filename=tvs-smf-1103', 'https://www.littelfuse.com/products/tvs-diodes/surface-mount/smf/smf18a.aspx', 'terra_sym:TVS Littlefuse SMF18A 18V 200W SOD-123-FL', 'Diode_SMD:D_SOD-123F', NULL, NULL, 'Active', 1, 'https://cdn1-originals.webdamdb.com/12956_132454242?cache=1649419592&response-content-disposition=inline;filename=CoC_RoHS9_SMF18A.pdf&response-content-type=application/pdf&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9jZG4xLW9yaWdpbmFscy53ZWJkYW1kYi5jb20vMTI5NTZfMTMyNDU0MjQyP2NhY2hlPTE2NDk0MTk1OTImcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1pbmxpbmU7ZmlsZW5hbWU9Q29DX1JvSFM5X1NNRjE4QS5wZGYmcmVzcG9uc2UtY29udGVudC10eXBlPWFwcGxpY2F0aW9uL3BkZiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MjE0NzQxNDQwMH19fV19&Signature=SghK7giE834PH39SnORD4PHdAb7ahUFUYY60Kukll3bJmZI1fPCtCwlkklOnZcG8RInYIMa-xkPiczriJ~DGrdYDjrfwctPSjwxhV53u2io1gItmmIRx85MVgFusCH-P-NPUkOXY8wylSI7r5SN1r7i4M~9pYh53rgjLKM7iHgj27ypV44FjEQmF9GbdUEfgUrlwaGFSLTfOui1RKxdVFqG~grnZgcDSMZYddzfQurFJloPlOcjw3EQp4pxZjhecafVlkAdKYL1aKSqFLGRcOLR720FLBHmknvFxLIK8TOPXkCweug5nvckzrMbAbaQOPFBTncDzz8K4RwPaQ08EAA__&Key-Pair-Id=APKAI2ASI2IOLRFF2RHA', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383299', '2025-11-11T22:05:47.383300', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/155C', '-65C/155C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS Littlefuse SMF6.0A 6V 200W SOD-123-FL', 'SMF6.0A', 'Littlefuse', 'SOD-123FL', '6V 200W', 'TVS, 6V working, 6.7V Breakdown, 10V Clamping, 200W SOD123FL', 'https://www.littelfuse.com/media?resourcetype=datasheets&itemid=7eb8a5b6-bdd0-4561-8f19-0c3cc6f9b2af&filename=tvs-smf-1103', 'https://www.littelfuse.com/products/tvs-diodes/surface-mount/smf/smf18a.aspx', 'terra_sym:TVS Littlefuse SMF6.0A 6V 200W SOD-123-FL', 'Diode_SMD:D_SOD-123F', NULL, NULL, 'Active', 1, 'https://cdn1-originals.webdamdb.com/12956_132454242?cache=1649419592&response-content-disposition=inline;filename=CoC_RoHS9_SMF18A.pdf&response-content-type=application/pdf&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9jZG4xLW9yaWdpbmFscy53ZWJkYW1kYi5jb20vMTI5NTZfMTMyNDU0MjQyP2NhY2hlPTE2NDk0MTk1OTImcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1pbmxpbmU7ZmlsZW5hbWU9Q29DX1JvSFM5X1NNRjE4QS5wZGYmcmVzcG9uc2UtY29udGVudC10eXBlPWFwcGxpY2F0aW9uL3BkZiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MjE0NzQxNDQwMH19fV19&Signature=SghK7giE834PH39SnORD4PHdAb7ahUFUYY60Kukll3bJmZI1fPCtCwlkklOnZcG8RInYIMa-xkPiczriJ~DGrdYDjrfwctPSjwxhV53u2io1gItmmIRx85MVgFusCH-P-NPUkOXY8wylSI7r5SN1r7i4M~9pYh53rgjLKM7iHgj27ypV44FjEQmF9GbdUEfgUrlwaGFSLTfOui1RKxdVFqG~grnZgcDSMZYddzfQurFJloPlOcjw3EQp4pxZjhecafVlkAdKYL1aKSqFLGRcOLR720FLBHmknvFxLIK8TOPXkCweug5nvckzrMbAbaQOPFBTncDzz8K4RwPaQ08EAA__&Key-Pair-Id=APKAI2ASI2IOLRFF2RHA', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383337', '2025-11-11T22:05:47.383339', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/155C', '-65C/155C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS MCC ESD12VD3B, 12V SMT', 'ESD12VD3B', 'Micro Commercial Components', 'SOD-323', '12V, 35kV', 'TVS, Working voltage 12V, +/-30kV SOD-323', 'https://www.mccsemi.com/pdf/Products/ESD12VD3B(SOD-323).pdf', 'https://www.mccsemi.com/product-detail/ESD12VD3B', 'terra_sym:TVS MCC ESD12VD3B, 12V SMT', 'nema:SOD-323-ESD12VD3B', NULL, NULL, 'Active', 1, 'https://www.mouser.com/catalog/additional/MCC_Certificate_of_RoHS_Compliance.pdf', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383370', '2025-11-11T22:05:47.383372', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/+150C', 'If applicable', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS SMT, Vishay, 30kV, 3V', ' VESD03C1-02V-G3-08', 'Vishay', 'SOD-523', 'TVS SMT, Vishay, 30kV, 3V', 'TVS 30kV, working voltage 3V', 'https://www.vishay.com/docs/86130/vesd01c1-02vtovesd33c1-02v.pdf', 'https://www.vishay.com/en/product/86130/', 'terra_sym:TVS SMT, Vishay, 30kV, 3V', 'nema:SOD-523', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.383399', '2025-11-11T22:05:47.383401', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/+150C', 'If applicable', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS SMT, Vishay, 3V/4.4V/8.7V 30kV SOD-523', ' VESD03C1-02V-G3-08', 'Vishay', 'SOD-523', 'TVS SMT, Vishay, 30kV, 3V', 'TVS 30kV, working voltage 3V', 'https://www.vishay.com/docs/86130/vesd01c1-02vtovesd33c1-02v.pdf', 'https://www.vishay.com/en/product/86130/', 'terra_sym:TVS SMT, Vishay, 3V/4.4V/8.7V 30kV SOD-523', 'nema:VESD01C1-02V-G3-08', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.383427', '2025-11-11T22:05:47.383429', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/+150C', 'If applicable', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS STMicro ESDA18-1K 15V/18V/34V SOD-523', ' ESDA18-1K ', 'STMicroelectronics', 'SOD-523', '18V', 'TVS, 18V working, 20 Breakdown, 29.2V Clamping, 200W SOD123FL', 'file:///Volumes/User/dave/Downloads/esda-1k.pdf', 'https://www.st.com/en/protections-and-emi-filters/esda-1k.html', 'terra_sym:TVS STMicro ESDA18-1K 15V/18V/34V SOD-523', 'Diode_SMD:D_SOD-523', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/SGST/SGST-E-A0010625279/SGST-E-A0010625279-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383455', '2025-11-11T22:05:47.383457', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/155C', '-65C/155C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS VMMBZ16C1DD1-G3-08 SMT, Vishay, 30kV, 14', 'VMMBZ16C1DD1-G3-08', 'Vishay', 'SOD-523', '14V, 30kv', 'TVS 30kV, working voltage 3V', 'https://www.vishay.com/docs/86193/vmmbz16c1dd1_to_vmmbz33c1dd1.pdf', 'https://www.vishay.com/en/product/86193/', 'terra_sym:TVS VMMBZ16C1DD1-G3-08 SMT, Vishay, 30kV, 14', 'nema:DFN1006-2B', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 0, 0, '1.1', NULL, '2025-11-11T22:05:47.383484', '2025-11-11T22:05:47.383486', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-55C/+150C', 'If applicable', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('TVS Vishay VESD05A1 5V/6V/12V SOD-523', 'VESD05A1-02VHG3-08', 'Littlefuse', 'SOD-523', '6V', 'TVS, 5V working, 6V Breakdown, 12V Clamping, 200W SOD-523', 'https://www.vishay.com/docs/86129/vesd05a1-02v.pdf', 'https://www.vishay.com/en/product/86129/', 'terra_sym:TVS Vishay VESD05A1 5V/6V/12V SOD-523', 'Diode_SMD:D_SOD-523', NULL, NULL, 'Active', 1, 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383527', '2025-11-11T22:05:47.383528', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-65C/155C', '-65C/155C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('ZENER SM712-02HTG 2 Channel', 'SM712-02HTG', 'Littlefuse', 'SOT-23-3', 'SM712-02HTG', '2-Channel ESD protection for RS-422, -7V/+12V, 30kV', 'https://www.littelfuse.com/media?resourcetype=datasheets&itemid=8313a28c-8802-4d47-a2a7-e30b5b1f67d8&filename=littelfuse-tvs-diode-array-sm712-datasheet', 'https://www.littelfuse.com/products/tvs-diode-arrays/general-purpose-esd-protection/sm712/sm712_02htg.aspx', 'terra_sym:ZENER SM712-02HTG 2 Channel', 'nema:SM71202HTG', NULL, NULL, 'Active', 1, 'https://cdn1-originals.webdamdb.com/12956_132452722?cache=1688003359&response-content-disposition=inline;filename=CoC_RoHS10_SM712-02HTG.pdf&response-content-type=application/pdf&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9jZG4xLW9yaWdpbmFscy53ZWJkYW1kYi5jb20vMTI5NTZfMTMyNDUyNzIyP2NhY2hlPTE2ODgwMDMzNTkmcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1pbmxpbmU7ZmlsZW5hbWU9Q29DX1JvSFMxMF9TTTcxMi0wMkhURy5wZGYmcmVzcG9uc2UtY29udGVudC10eXBlPWFwcGxpY2F0aW9uL3BkZiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MjE0NzQxNDQwMH19fV19&Signature=axa6TOgg2LJfBoNBAskOKMZ7QQmsKn2BX8nXCi1xs3x9HadBoRWKwWEtB~NuuR4DCDBcofs0J36KJJs5yN8jVrl9F7ZKreWeHMSS01hLjuQAiK2SSGoXhltSwTvPUC~anHKkFoM7Wo8Ck2RQKw38oOBaOAWr-dlLblz8QW0AuEYKLiI3WXelsuk3Ytf~mOzDXYzHoUhJ60TxzsyX0hccBIp4Ue-ZXZNe-a~t2PobhxxLAvZuqZQA6dEAd3jekdu15DA-TVUEOv0wslzXVHw7dV8V-82Ji5E3aeupWmqFX0QU2Nyl~enB~Sldg6vhNyLId8DzEWXPNELT8s1l3mLJOw__&Key-Pair-Id=APKAI2ASI2IOLRFF2RHA', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383681', '2025-11-11T22:05:47.383683', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40/+125C', '-50/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('ZENER SM712-02HTG 2 Channel_1', 'SM712-02HTG', 'Littlefuse', 'SOT-23-3', 'SM712-02HTG', '2-Channel ESD protection for RS-422, -7V/+12V, 30kV', 'https://www.littelfuse.com/media?resourcetype=datasheets&itemid=8313a28c-8802-4d47-a2a7-e30b5b1f67d8&filename=littelfuse-tvs-diode-array-sm712-datasheet', 'https://www.littelfuse.com/products/tvs-diode-arrays/general-purpose-esd-protection/sm712/sm712_02htg.aspx', 'terra_sym:ZENER SM712-02HTG 2 Channel_1', 'nema:SM71202HTG', NULL, NULL, 'Active', 1, 'https://cdn1-originals.webdamdb.com/12956_132452722?cache=1688003359&response-content-disposition=inline;filename=CoC_RoHS10_SM712-02HTG.pdf&response-content-type=application/pdf&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9jZG4xLW9yaWdpbmFscy53ZWJkYW1kYi5jb20vMTI5NTZfMTMyNDUyNzIyP2NhY2hlPTE2ODgwMDMzNTkmcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1pbmxpbmU7ZmlsZW5hbWU9Q29DX1JvSFMxMF9TTTcxMi0wMkhURy5wZGYmcmVzcG9uc2UtY29udGVudC10eXBlPWFwcGxpY2F0aW9uL3BkZiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MjE0NzQxNDQwMH19fV19&Signature=axa6TOgg2LJfBoNBAskOKMZ7QQmsKn2BX8nXCi1xs3x9HadBoRWKwWEtB~NuuR4DCDBcofs0J36KJJs5yN8jVrl9F7ZKreWeHMSS01hLjuQAiK2SSGoXhltSwTvPUC~anHKkFoM7Wo8Ck2RQKw38oOBaOAWr-dlLblz8QW0AuEYKLiI3WXelsuk3Ytf~mOzDXYzHoUhJ60TxzsyX0hccBIp4Ue-ZXZNe-a~t2PobhxxLAvZuqZQA6dEAd3jekdu15DA-TVUEOv0wslzXVHw7dV8V-82Ji5E3aeupWmqFX0QU2Nyl~enB~Sldg6vhNyLId8DzEWXPNELT8s1l3mLJOw__&Key-Pair-Id=APKAI2ASI2IOLRFF2RHA', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383711', '2025-11-11T22:05:47.383713', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40/+125C', '-50/+150C', NULL);
INSERT INTO diodes ("part_id", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "diode_type", "forward_voltage", "forward_current", "reverse_voltage", "reverse_current", "power_dissipation", "recovery_time", "capacitance", "zener_voltage", "clamping_voltage", "temp_operating", "temp_storage", "temp_junction_max") VALUES ('ZENER SM712-02HTG 2 Channel_parallel', 'SM712-02HTG', 'Littlefuse', 'SOT-23-3', 'SM712-02HTG', '2-Channel ESD protection for RS-422, -7V/+12V, 30kV', 'https://www.littelfuse.com/media?resourcetype=datasheets&itemid=8313a28c-8802-4d47-a2a7-e30b5b1f67d8&filename=littelfuse-tvs-diode-array-sm712-datasheet', 'https://www.littelfuse.com/products/tvs-diode-arrays/general-purpose-esd-protection/sm712/sm712_02htg.aspx', 'terra_sym:ZENER SM712-02HTG 2 Channel_parallel', 'nema:SM71202HTG', NULL, NULL, 'Active', 1, 'https://cdn1-originals.webdamdb.com/12956_132452722?cache=1688003359&response-content-disposition=inline;filename=CoC_RoHS10_SM712-02HTG.pdf&response-content-type=application/pdf&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9jZG4xLW9yaWdpbmFscy53ZWJkYW1kYi5jb20vMTI5NTZfMTMyNDUyNzIyP2NhY2hlPTE2ODgwMDMzNTkmcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1pbmxpbmU7ZmlsZW5hbWU9Q29DX1JvSFMxMF9TTTcxMi0wMkhURy5wZGYmcmVzcG9uc2UtY29udGVudC10eXBlPWFwcGxpY2F0aW9uL3BkZiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MjE0NzQxNDQwMH19fV19&Signature=axa6TOgg2LJfBoNBAskOKMZ7QQmsKn2BX8nXCi1xs3x9HadBoRWKwWEtB~NuuR4DCDBcofs0J36KJJs5yN8jVrl9F7ZKreWeHMSS01hLjuQAiK2SSGoXhltSwTvPUC~anHKkFoM7Wo8Ck2RQKw38oOBaOAWr-dlLblz8QW0AuEYKLiI3WXelsuk3Ytf~mOzDXYzHoUhJ60TxzsyX0hccBIp4Ue-ZXZNe-a~t2PobhxxLAvZuqZQA6dEAd3jekdu15DA-TVUEOv0wslzXVHw7dV8V-82Ji5E3aeupWmqFX0QU2Nyl~enB~Sldg6vhNyLId8DzEWXPNELT8s1l3mLJOw__&Key-Pair-Id=APKAI2ASI2IOLRFF2RHA', 1, 0, '1.1', NULL, '2025-11-11T22:05:47.383743', '2025-11-11T22:05:47.383747', 'migration_script', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '-40/+125C', '-50/+150C', NULL);

COMMIT;
