#!/usr/bin/env python3
"""Harvest curated diodes from the abc4-spiro-cart cartridge board into native terra.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("diodes_generated_310_cart_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "diode_type", "voltage_rating", "power_rating",
]

PARTS = [
    {
        "mpn": "ESDA18-1K", "manufacturer": "STMicroelectronics",
        "package": "SOD-523", "value": "18V",
        "description": "STMicroelectronics ESDA18-1K unidirectional TVS / ESD protection diode, 18V working, SOD-523",
        "datasheet": "https://www.st.com/resource/en/datasheet/esda18-1k.pdf",
        "manufacturer_link": "https://www.st.com",
        "kicad_symbol": "Device:D_TVS",
        "kicad_footprint": "Diode_SMD:D_SOD-523",
        "pin_count": "2", "diode_type": "tvs",
        "voltage_rating": "18V", "power_rating": None,
        "keywords": "tvs,esd,protection",
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def part_locator(p):
    return f"diode-{p['diode_type']}-{p['value'].lower().replace(' ', '-')}-{p['package'].lower()}"


def main():
    lines = [
        "-- Terra EDA Library - diodes harvest from abc4-spiro-cart cartridge board",
        f"-- Curated diode parts ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        rec = {
            "unique_id": f"{p['manufacturer'].replace(' ', '_')}-{p['mpn']}",
            "part_locator": part_locator(p),
            "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
            "source": None, "dump_priority": 0, "tier": 2,
        }
        rec.update(p)
        vals = ", ".join(sql(rec.get(c)) for c in COLS)
        lines.append(f"INSERT INTO diodes ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
