-- KiCad Symbol Library SQL Script
-- Generated from: terra_sym.kicad_sym
-- Number of symbols: 6 (3 LED drivers removed; see db/tables/led_drivers/)
--
-- To create the database, run:
--   sqlite3 output.db < leds_1_migrated.sql
--

-- Create symbols table

BEGIN TRANSACTION;

INSERT INTO optoelectronics_led ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "sim_device", "sim_pins", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering") VALUES ('Broadcom-HSML-A401-U40M1', 'LED Broadcom Orange, PLCC-4  HSML-A401-U40M1 ', 'HSML-A401-U40M1', 'Broadcom', 'SMT', 'LED Broadcom Orange, PLCC-4  HSML-A401-U40M1', 'Orange SMT LED , PLCC-4 SMT', 'https://docs.broadcom.com/docs/HSMx-A4xx-xxxxx-SMT-Surface-Mount-LED-Indicator-DS', 'https://www.broadcom.com/products/leds-and-displays/surface-mount-plcc/plcc-4-leds/flat-top/hsml-a401-u40m1', 'terra_sym:LED Broadcom Orange, PLCC-4  HSML-A401-U40M1 ', 'terra_sym:ASMT-SWB5-NW703', 'Yes', 'https://www.mouser.com/catalog/additional/Broadcom_Limited_6305_RoHS_Certificate.pdf', 'No', 'No', '1.1', 'terra_sym', '100', 'D', '1=K 2=A', -40, 100, -40, 100, 260);
INSERT INTO optoelectronics_led ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "sim_device", "sim_pins", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering") VALUES ('Broadcom-ASMT-SWB5-NW703', 'LED Broadcom White, PLCC-4 ASMT-SWB5-NW703', 'ASMT-SWB5-NW703', 'Broadcom', 'SMT', 'LED Broadcom White, PLCC-4 ASMT-SWB5-NW703', 'White SMT LED , PLCC-4 SMT', 'https://docs.broadcom.com/docs/ASMT-SWB5-Nxxxx-DS', 'https://www.broadcom.com/products/leds-and-displays/surface-mount-plcc/plcc-4-leds/flat-top/asmt-swb5-nw703', 'terra_sym:LED Broadcom White, PLCC-4 ASMT-SWB5-NW703', 'terra_sym:ASMT-SWB5-NW703', 'Yes', 'https://www.mouser.com/catalog/additional/Broadcom_6305_RoHS_Certificate.pdf', 'No', 'No', '1.1', 'terra_sym', '100', 'D', '1=K 2=A', -40, 100, -40, 100, 260);
INSERT INTO optoelectronics_led ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "sim_device", "sim_pins", "pin_count", "temp_operating_min", "temp_operating_max") VALUES ('Kingsbright-APHBM2012CGKSYKC', 'LED DUAL APHBM2012CGKSYKC ', 'APHBM2012CGKSYKC', 'Kingsbright', 'SMD', 'LED DUAL APHBM2012CGKSYKC', 'Dual Green/Yellow LED, SMD', 'https://www.kingbrightusa.com/images/catalog/SPEC/APHBM2012CGKSYKC.pdf', 'https://www.kingbrightusa.com/product.asp?catalog_name=LED&product_id=APHBM2012CGKSYKC', 'terra_sym:LED DUAL APHBM2012CGKSYKC ', 'Yes', 'https://www.mouser.com/catalog/additional/Kingbright_6040_RoHS_Certificate.pdf', 'Yes', 'No', '1.1', 'terra_sym', '100', 'D', '1=K 2=A', '4', -40, 85);
INSERT INTO optoelectronics_led ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "sim_device", "sim_pins", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering") VALUES ('Dialight-550-0205F', 'LED Dialight CBI 5mm Green TH', '550-0205F', 'Dialight', 'TH CBI', 'Green', 'CBI 1x1 5mm green LED', 'https://s3-us-west-2.amazonaws.com/catsy.557/C17264.pdf', 'https://www.dialightsignalsandcomponents.com/550-series-cbi-5mm-1x1-g/#resources-btn', 'terra_sym:LED Dialight CBI 5mm Green TH', 'terra_sym:Dialight-550-series', 'Yes', 'https://www.dialightsignalsandcomponents.com/550-series-cbi-5mm-1x1-g/#resources-btn', 'Yes', 'No', '1.1', 'terra_sym', '100', 'D', '1=K 2=A', -40, 100, -40, 100, 260);
INSERT INTO optoelectronics_led ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "sim_device", "sim_pins", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering") VALUES ('Dialight-550-3507F', 'LED Dialight CBI 5mm Green/Red Common Cath TH', '550-3507F', 'Dialight', 'TH CBI', 'Green/Red', 'CBI 1x1 5mm Green/Red Commong Cathode LED', 'https://s3-us-west-2.amazonaws.com/catsy.557/C17264.pdf', 'https://www.dialightsignalsandcomponents.com/550-series-5-mm-cbi-r-g-3-leaded-slope-back-housing/', 'terra_sym:LED Dialight CBI 5mm Green/Red Common Cath TH', 'terra_sym:Dialight-550-3x07', 'Yes', 'https://www.dialightsignalsandcomponents.com/550-series-5-mm-cbi-r-g-3-leaded-slope-back-housing/', 'Yes', 'No', '1.1', 'terra_sym', '100', 'D', '1=K 2=A', -20, 85, -55, 100, 260);
INSERT INTO optoelectronics_led ("unique_id", "part_locator", "mpn", "manufacturer", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "source", "dump_priority", "sim_device", "sim_pins", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering") VALUES ('Kingbright- APG1608QBC/D ', 'LED Kingbright Blue  SMT 1608  APG1608QBC/D', ' APG1608QBC/D ', 'Kingbright', '1608', 'LED', 'Blue LED  SMT 1608  20mA', 'https://www.kingbrightusa.com/images/catalog/SPEC/APG1608QBC-D.pdf', 'http://www.kingbrightusa.com/product.asp?catalog_name=LED&product_id=APG1608QBC/D', 'terra_sym:LED Kingbright Blue  SMT 1608  APG1608QBC/D', 'terra_sym:LED_0603_1608Metric', 'Yes', 'https://www.mouser.com/catalog/additional/Kingbright_6040_RoHS_Certificate.pdf', 'Yes', 'No', '1.1', 'terra_sym', '100', 'D', '1=K 2=A', -40, 85, -40, 85, 260);

COMMIT;
