#!/usr/bin/env python3
"""Harvest the curated Everlight green LED from the abc4-spiro-cart board into terra.

LED1/LED2 on cartridge-pcb are the same Everlight 19-219/GHC-YR2T1B5Y/3T (525nm green,
1608 SMD). The schematic referenced a one-off native symbol with an empty MPN, so it had
no terra database part. It is a plain two-pin LED, so it uses the standard KiCad Device:LED
symbol; the footprint is terra's existing terra-optoelectronics:LED_0603_1608Metric (standard 1608 land
with the migrated APG1608.STEP 3D model), the same footprint the sibling Kingbright 1608 LED
uses -- not the generic LED_SMD footprint, which would drop the curated 3D model.

Deep electrical params (Vf, If max, viewing angle) are left NULL for the parametric harvest
pass; the identity and optical descriptors come from the curated symbol + datasheet.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("optoelectronics_led_generated_320_cart_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "color", "wavelength_nm", "luminous_intensity",
    "forward_voltage_v", "current_max_ma", "viewing_angle",
]

PARTS = [
    {
        "unique_id": "Everlight-19-219/GHC-YR2T1B5Y/3T",
        "part_locator": "led-green-525nm-1608-smd",
        "mpn": "19-219/GHC-YR2T1B5Y/3T", "manufacturer": "Everlight",
        "package": "1608", "value": "Green",
        "description": "Everlight 19-219/GHC-YR2T1B5Y/3T green LED, 525nm, 360mcd, 1608 (0603) SMD",
        "datasheet": "${TERRA_EDA_LIB}/datasheets/everlight/19-219-ghc-yr2t1b5y.pdf",
        "manufacturer_link": "https://www.everlighteurope.com/product-details?id=2934",
        "kicad_symbol": "Device:LED",
        "kicad_footprint": "terra-optoelectronics:LED_0603_1608Metric",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "keywords": "led,green,optical,smd", "pin_count": "2",
        "color": "Green", "wavelength_nm": "525", "luminous_intensity": "360 mcd",
        # Everlight 19-219 DS: Vf 2.9V typ @ 5mA, If max 25mA, 2theta-1/2 130 deg.
        "forward_voltage_v": "2.9 V", "current_max_ma": "25 mA",
        "viewing_angle": "130 deg",
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - LED harvest from abc4-spiro-cart board",
        f"-- Curated LED ported as a native terra row. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO optoelectronics_led ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
