#!/usr/bin/env python3
"""Harvest a curated Murata MLCC from the abc4-spiro-cart board into capacitors_smt.

GRM155Z71A105KE01D (1uF X7R 0402 10V) is a Murata specialty part -- Samsung's CL
line tops out at 6.3V for 1uF/X7R/0402, so the generated Samsung family can't cover
it. Ported here as a single validated part from its datasheet
(datasheets/murata/grm155z71a105ke01.pdf). A full Murata GRM15 family generator
would need a Murata parametric catalog CSV (the datasheet gives the part-number
convention but no lineup of which combinations exist).

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("capacitors_smt_generated_310_cart_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "tags", "pin_count",
    "voltage_rating_v", "tolerance", "cap_type", "dielectric_class", "polarized",
    "temp_operating_min", "temp_operating_max",
]

PARTS = [
    {
        "unique_id": "Murata-GRM155Z71A105KE01D",
        "part_locator": "cap-mlcc-1u-10v-x7r-0402",
        "mpn": "GRM155Z71A105KE01D", "manufacturer": "Murata",
        "package": "0402", "value": "1u",
        "description": "Murata GRM155Z71A105KE01D 1uF X7R 10V +/-10% MLCC, 0402",
        "datasheet": "${TERRA_EDA_LIB}/datasheets/murata/grm155z71a105ke01.pdf",
        "manufacturer_link": "https://www.murata.com/en-us/products/productdetail?partno=GRM155Z71A105KE01%23",
        "kicad_symbol": "Device:C",
        "kicad_footprint": "Capacitor_SMD:C_0402_1005Metric",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "tags": "capacitor,mlcc", "pin_count": "2",
        "voltage_rating_v": 10.0, "tolerance": "10%", "cap_type": "MLCC",
        "dielectric_class": "X7R", "polarized": "No",
        "temp_operating_min": -55.0, "temp_operating_max": 125.0,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - Murata MLCC harvest from abc4-spiro-cart board",
        f"-- Curated specialty MLCC ported as a native terra row. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO capacitors_smt ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
