#!/usr/bin/env python3
"""Microchip megaAVR (ATmega) 8-bit microcontroller family.

One row per (device x package). Symbols are KiCad's stock
MCU_Microchip_ATmega:<device>-<pkgsuffix>; footprints are KiCad standard, picked
from each symbol's ki_fp_filters. Data-driven: DEVICES holds the shared per-chip
specs, VARIANTS the orderable packages -- extend both to grow the family.

Starting with ATmega328P and ATmega2560.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ic_microcontrollers_generated_310_atmega.sql")
CREATED_BY = Path(__file__).name
SYMLIB = "MCU_Microchip_ATmega:"

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "temp_operating_min", "temp_operating_max",
    "family", "core", "architecture_bits", "max_clock", "active_current",
    "sleep_current", "supply_voltage_min", "supply_voltage_max",
    "flash_size", "eeprom_size", "ram_size", "gpio_count", "uart_count",
    "i2c_count", "spi_count", "usb_count", "can_count", "eth_count",
    "timer_count", "pwm_count", "dma_count", "adc_count", "adc_resolution",
    "dac_count", "special_features",
]

DEFAULTS = dict(
    manufacturer="Microchip", rohs="Yes", allow_substitution="No", tracking="No",
    source=None, dump_priority=0, tier=2,
    family="megaAVR", core="AVR", architecture_bits=8,
    temp_operating_min=-40, temp_operating_max=85,
    usb_count=0, can_count=0, eth_count=0, dma_count=0, dac_count=0,
    adc_resolution="10-bit", sleep_current="0.1µA (power-down)",
)

# device -> shared electrical/peripheral specs
DEVICES = {
    "ATmega328P": dict(
        flash_size="32KB", eeprom_size="1KB", ram_size="2KB", max_clock="20MHz",
        supply_voltage_min=1.8, supply_voltage_max=5.5,
        active_current="0.2mA @ 1MHz/1.8V",
        gpio_count=23, uart_count=1, i2c_count=1, spi_count=1,
        timer_count=3, pwm_count=6,
        manufacturer_link="https://www.microchip.com/en-us/product/atmega328p",
        datasheet="${TERRA_EDA_LIB}/datasheets/microchip/atmega328p.pdf",
        keywords="mcu,microcontroller,avr,8-bit,megaavr,atmega328p,arduino",
        special_features="watchdog, brown-out detect, internal RC oscillator"),
    "ATmega2560": dict(
        flash_size="256KB", eeprom_size="4KB", ram_size="8KB", max_clock="16MHz",
        supply_voltage_min=4.5, supply_voltage_max=5.5,
        active_current="5mA @ 8MHz/5V",
        gpio_count=86, uart_count=4, i2c_count=1, spi_count=1,
        timer_count=6, pwm_count=15,
        manufacturer_link="https://www.microchip.com/en-us/product/atmega2560",
        datasheet="${TERRA_EDA_LIB}/datasheets/microchip/atmega2560.pdf",
        keywords="mcu,microcontroller,avr,8-bit,megaavr,atmega2560,arduino-mega",
        special_features="watchdog, brown-out detect, JTAG"),
}

# device -> [(package, mpn, pin_count, symbol_name, kicad_footprint, adc_count)]
VARIANTS = {
    "ATmega328P": [
        ("PDIP-28", "ATMEGA328P-PU", "28", "ATmega328P-P", "Package_DIP:DIP-28_W7.62mm", 6),
        ("TQFP-32", "ATMEGA328P-AU", "32", "ATmega328P-A", "Package_QFP:TQFP-32_7x7mm_P0.8mm", 8),
        ("QFN-32", "ATMEGA328P-MU", "32", "ATmega328P-M", "Package_DFN_QFN:QFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm", 8),
        ("VQFN-28", "ATMEGA328P-MMH", "28", "ATmega328P-MM", "Package_DFN_QFN:QFN-28-1EP_4x4mm_P0.45mm_EP2.4x2.4mm", 6),
    ],
    "ATmega2560": [
        ("TQFP-100", "ATMEGA2560-16AU", "100", "ATmega2560-16A", "Package_QFP:TQFP-100_14x14mm_P0.5mm", 16),
    ],
}


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - Microchip megaAVR (ATmega) microcontrollers",
        f"-- Generated by {CREATED_BY}. dump_priority=0, source=NULL: not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    seen = set()
    for device, base in DEVICES.items():
        for package, mpn, pin_count, sym, fp, adc in VARIANTS[device]:
            uid = f"Microchip-{mpn}"
            if uid in seen:
                raise SystemExit(f"duplicate unique_id: {uid}")
            seen.add(uid)
            pkgtoken = package.lower().replace(" ", "")
            row = {**DEFAULTS, **base,
                   "unique_id": uid, "value": device,
                   "part_locator": f"mcu-avr-{device.lower()}-{pkgtoken}",
                   "mpn": mpn, "package": package, "pin_count": pin_count,
                   "kicad_symbol": SYMLIB + sym, "kicad_footprint": fp,
                   "adc_count": adc,
                   "description": f"8-bit AVR MCU, {base['flash_size']} Flash, "
                                  f"{base['ram_size']} SRAM, {package}"}
            vals = ", ".join(sql(row.get(c)) for c in COLS)
            lines.append(f"INSERT INTO ic_microcontrollers ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(seen)} rows across {len(DEVICES)} devices")


if __name__ == "__main__":
    main()
