#!/usr/bin/env python3
"""Emit the ic_microcontrollers catalog harvested from terra_sym.kicad_sym as native rows.

These two parts were previously the hand-converted ic_microcontrollers dump
(itself generated from terra_sym.kicad_sym). They are scripted here so a schema
change reapplies by rebuild.

Deferred curation: the deep tail (family, core, flash_size, ram_size,
eeprom_size, gpio_count, supply_voltage, peripheral counts) is entirely NULL and
needs a datasheet harvest. Both rows are the same SAMC20 die in different
pin-count packages (E18A=32-pin, G18A=48-pin).

Generated output (dump_priority=0) is not dumped back to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ic_microcontrollers_generated_300_terra_sym_harvest.sql")

DS = "https://ww1.microchip.com/downloads/en/DeviceDoc/SAMC20_C21_Family_Data_Sheet_DS60001479D.pdf"
ROHS_CR = "https://4donline.ihs.com/images/VipMasterIC/IC/MCHP/MCHP-E-A0019744312/MCHP-E-A0019744312-1.pdf?hkey=6D0214268300F1406B835FE51CB13195"

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution",
    "tracking", "standards_version", "source", "dump_priority", "tier",
    "pin_count", "temp_operating_min", "temp_operating_max", "temp_storage_min",
    "temp_storage_max",
    "family", "core", "supply_voltage_min", "supply_voltage_max",
    "flash_size", "eeprom_size", "ram_size", "gpio_count", "uart_count",
    "i2c_count", "timer_count", "special_features",
]

PARTS = [
    {
        "unique_id": "Microchip-ATSAMC20E18A",
        "part_locator": "IC_MCU ATSAMC20E18A-AUT 256 KB 5V TQFP-32",
        "mpn": "ATSAMC20E18A", "manufacturer": "Microchip", "package": "TQFP-32",
        "value": "ATSAMC20E18A",
        "description": "Arm MCU, 5V, 256KB, TQFP-32",
        "datasheet": DS,
        "manufacturer_link": "https://www.microchip.com/en-us/product/atsamc20e18a",
        "kicad_symbol": "terra_symbols_ic_microcontrollers:IC_MCU ATSAMC20E18A-AUT 256 KB 5V TQFP-32",
        "kicad_footprint": "Package_QFP:TQFP-32_7x7mm_P0.8mm",
        "rohs": "Yes", "rohs_document_link": ROHS_CR,
        "allow_substitution": "Yes", "tracking": "Yes", "standards_version": "1.1",
        "source": "terra_sym", "dump_priority": 0, "tier": 2, "pin_count": "32",
        "temp_operating_min": -40, "temp_operating_max": 85,
        "temp_storage_min": -60, "temp_storage_max": 150,
        "family": "SAM C20", "core": "Arm Cortex-M0+",
        "supply_voltage_min": 2.7, "supply_voltage_max": 5.5,
        "flash_size": "256 KB", "ram_size": "32 KB",
        "gpio_count": 26, "uart_count": 4, "i2c_count": 4, "timer_count": 8,
        "special_features": "12-bit ADC, PTC, DIVAS, CCL, RWW Flash EEPROM emulation",
    },
    {
        "unique_id": "Microchip-ATSAMC20G18A",
        "part_locator": "IC_MCU ATSAMC20G18A-AUT 256 KB 5V TQFP-48",
        "mpn": "ATSAMC20G18A", "manufacturer": "Microchip", "package": "TQFP-48",
        "value": "ATSAMC20G18A",
        "description": "Arm MCU, 5V, 256KB, TQFP-48",
        "datasheet": DS,
        "manufacturer_link": "https://www.microchip.com/en-us/product/atsamc20g18a",
        "kicad_symbol": "terra_symbols_ic_microcontrollers:IC_MCU ATSAMC20G18A-AUT 256 KB 5V TQFP-48",
        "kicad_footprint": "Package_QFP:TQFP-48_7x7mm_P0.5mm",
        "rohs": "Yes", "rohs_document_link": ROHS_CR,
        "allow_substitution": "Yes", "tracking": "Yes", "standards_version": "1.1",
        "source": "terra_sym", "dump_priority": 0, "tier": 2, "pin_count": "48",
        "temp_operating_min": -40, "temp_operating_max": 85,
        "temp_storage_min": -60, "temp_storage_max": 150,
        "family": "SAM C20", "core": "Arm Cortex-M0+",
        "supply_voltage_min": 2.7, "supply_voltage_max": 5.5,
        "flash_size": "256 KB", "ram_size": "32 KB",
        "gpio_count": 38, "uart_count": 4, "i2c_count": 4, "timer_count": 8,
        "special_features": "12-bit ADC, PTC, DIVAS, CCL, RWW Flash EEPROM emulation",
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - ic_microcontrollers harvested from terra_sym.kicad_sym",
        f"-- Native terra rows scripted from the terra_sym source. Generated by {Path(__file__).name}.",
        "-- dump_priority=0: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO ic_microcontrollers ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
