#!/usr/bin/env python3
"""Emit the ic_memory catalog harvested from terra_sym.kicad_sym as native rows.

This single part was recovered from the terra_sym.kicad_sym source. It is scripted
here so a schema change reapplies by rebuild and the part shares one parameter set.

Only typos contradicted by a part's own other fields are corrected here: the mpn
carried a leading space (" 24LC32AT-I/OT") -> trimmed; unique_id follows.

Deferred curation: the kicad_footprint is `terra-ic-memory:`-prefixed
(terra-ic-memory:SOT95P270X145-5N) and needs a real SOT-23-5 footprint; capacity
('4k x 8' / 32 Kbit) and interface ('I2C') are evident from the value/description
but left NULL pending curation; word_size and speed also need a datasheet harvest.

Generated output (dump_priority=0) is not dumped back to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ic_memory_generated_300_terra_sym_harvest.sql")

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution",
    "tracking", "standards_version", "source", "dump_priority", "tier",
    "pin_count", "temp_operating_min", "temp_operating_max", "temp_storage_min",
    "temp_storage_max", "memory_type", "capacity", "word_size", "speed",
    "interface", "persistence_cycles", "persistence_years",
]

PARTS = [
    {
        # FIX: mpn carried a leading space (" 24LC32AT-I/OT") -> trimmed; unique_id follows.
        "unique_id": "Microchip-24LC32AT-I/OT",
        "part_locator": "IC_MEMORY EEPROM Microchip 24LC32A 4kx8 SOT-23-5",
        "mpn": "24LC32AT-I/OT", "manufacturer": "Microchip", "package": "SOT-23-5",
        "value": "4k x 8 EEPROM",
        "description": "EEPROM 4k x 8 I2C SOT-23-5",
        "datasheet": "https://ww1.microchip.com/downloads/aemDocuments/documents/MPD/ProductDocuments/DataSheets/24AA32A-24LC32A-32-Kbit-I2C-Serial-EEPROM-DS20001713.pdf",
        "manufacturer_link": "https://www.microchip.com/en-us/product/24lc32a",
        "kicad_symbol": "terra-ic-memory:IC_MEMORY EEPROM Microchip 24LC32A 4kx8 SOT-23-5",
        "kicad_footprint": "terra-ic-memory:SOT95P270X145-5N",
        "rohs": "Yes",
        "rohs_document_link": "https://4donline.ihs.com/images/VipMasterIC/IC/MCHP/MCHP-E-A0019744312/MCHP-E-A0019744312-1.pdf?hkey=6D0214268300F1406B835FE51CB13195",
        "allow_substitution": "Yes", "tracking": "No", "standards_version": "1.1",
        "source": "terra_sym", "dump_priority": 0, "tier": 2, "pin_count": "5",
        "temp_operating_min": -40, "temp_operating_max": 85,
        "temp_storage_min": -40, "temp_storage_max": 85, "memory_type": "EEPROM",
        "capacity": "32 Kbit", "word_size": "8-bit", "speed": "400 kHz",
        "interface": "I2C", "persistence_cycles": "1M",
        "persistence_years": "200 years",
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - ic_memory harvested from terra_sym.kicad_sym",
        f"-- Native terra rows scripted from the terra_sym source. Generated by {Path(__file__).name}.",
        "-- dump_priority=0: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO ic_memory ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
