#!/usr/bin/env python3
"""Microchip 24LC32A (32 Kbit I2C serial EEPROM) package family.

The SOT-23-5 variant was recovered from terra_sym.kicad_sym; the 8-pin packages
are added on KiCad's stock Memory_EEPROM:24LC32 symbol and standard footprints.
Note the SOT-23-5 (OT) part is the reduced 5-pin variant (no A0/A1/A2 address
pins) so it keeps its own curated 5-pin terra symbol; the 8-pin packages share
KiCad's 24LC32 symbol (A0/A1/A2/VSS/SDA/SCL/WP/VCC). The DFN-8 (MNY) package is
omitted pending exposed-pad confirmation (KiCad has several DFN-8 3x2mm EP sizes).

Generated output (dump_priority=0) is not dumped back to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ic_memory_generated_300_terra_sym_harvest.sql")

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "rohs_document_link", "allow_substitution",
    "tracking", "standards_version", "source", "dump_priority", "tier",
    "pin_count", "temp_operating_min", "temp_operating_max", "temp_storage_min",
    "temp_storage_max", "memory_type", "capacity", "word_size", "speed",
    "interface", "persistence_cycles", "persistence_years",
]

COMMON = dict(
    manufacturer="Microchip", value="4k x 8 EEPROM",
    datasheet="${TERRA_EDA_LIB}/datasheets/microchip/24lc32a.pdf",
    manufacturer_link="https://www.microchip.com/en-us/product/24lc32a",
    rohs="Yes",
    rohs_document_link="https://4donline.ihs.com/images/VipMasterIC/IC/MCHP/MCHP-E-A0019744312/MCHP-E-A0019744312-1.pdf?hkey=6D0214268300F1406B835FE51CB13195",
    allow_substitution="Yes", tracking="No", standards_version="1.1",
    source="terra_sym", dump_priority=0, tier=2,
    temp_operating_min=-40, temp_operating_max=85,
    temp_storage_min=-40, temp_storage_max=85, memory_type="EEPROM",
    capacity="32 Kbit", word_size="8-bit", speed="400 kHz", interface="I2C",
    persistence_cycles="1M", persistence_years="200 years",
)

EEPROM8 = "Memory_EEPROM:24LC32"   # stock 8-pin I2C EEPROM symbol

# (mpn, package, pin_count, kicad_symbol, kicad_footprint)
VARIANTS = [
    ("24LC32AT-I/OT", "SOT-23-5", "5",
     "terra_symbols_ic_memory:IC_MEMORY EEPROM Microchip 24LC32A 4kx8 SOT-23-5",
     "Package_TO_SOT_SMD:SOT-23-5"),
    ("24LC32A-I/P", "PDIP-8", "8", EEPROM8, "Package_DIP:DIP-8_W7.62mm"),
    ("24LC32A-I/SN", "SOIC-8", "8", EEPROM8, "Package_SO:SOIC-8_3.9x4.9mm_P1.27mm"),
    ("24LC32AT-I/ST", "TSSOP-8", "8", EEPROM8, "Package_SO:TSSOP-8_4.4x3mm_P0.65mm"),
]

PARTS = [
    {**COMMON,
     "unique_id": f"Microchip-{mpn}",
     "part_locator": f"IC_MEMORY EEPROM Microchip 24LC32A 4kx8 {pkg}",
     "mpn": mpn, "package": pkg, "description": f"EEPROM 4k x 8 I2C {pkg}",
     "kicad_symbol": sym, "kicad_footprint": fp, "pin_count": pins}
    for mpn, pkg, pins, sym, fp in VARIANTS
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - Microchip 24LC32A I2C EEPROM package family",
        f"-- Generated by {Path(__file__).name}. dump_priority=0: not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO ic_memory ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
