#!/usr/bin/env python3
"""Emit the switches catalog harvested from terra_sym.kicad_sym as native rows.

The recovered terra_sym dump for this table held two rows, but only one is a
switch. This generator ports just the CK Components DF62J12S2AHQAA DPDT rocker
and faithfully preserves every field from its source row.

Deferred curation: the kicad_footprint is `terra-switches:`-prefixed, so it points at
a symbol library rather than a real footprint and needs a proper footprint later.
The deep tail (switch_type, poles, throws, voltage_rating, actuation_force) is
NULL pending a datasheet harvest -- the datasheet describes a DPDT rocker,
right-angle, through-hole. Separately, a mis-filed white PLCC-4 LED
(Broadcom ASMT-SWB5-NW703, sim_device='L') was dropped from this table; it is a
duplicate of a part that belongs in optoelectronics_led, not switches.

Generated output (dump_priority=0) is not dumped back to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("switches_generated_300_terra_sym_harvest.sql")

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "value", "description",
    "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "rohs",
    "rohs_document_link", "allow_substitution", "tracking", "standards_version",
    "source", "dump_priority", "tier", "pin_count", "temp_operating_min",
    "temp_operating_max", "current_rating", "switch_type", "poles", "throws",
    "voltage_rating", "actuation_force",
]

PARTS = [
    {
        "unique_id": "CK Components-DF62J12S2AHQAA",
        "part_locator": "SW DPDT CK DF62J12S2AHQAA ",
        "mpn": "DF62J12S2AHQAA", "manufacturer": "CK Components",
        "value": "SW DPDT CK DF62J12S2AHQAA",
        "description": "DPDT rocker, right angle, through-hole",
        "datasheet": "${TERRA_EDA_LIB}/datasheets/ck/df-series.pdf",
        "manufacturer_link": "https://www.ckswitches.com/products/switches/product-details/Rocker/DF/DF62J12S2AHQA/",
        "kicad_symbol": "terra_symbols_switches:SW DPDT CK DF62J12S2AHQAA ",
        "kicad_footprint": "terra_footprints_switches:CK_DF62J12S2AHQAA",
        "rohs": "Yes",
        "rohs_document_link": "https://www.mouser.com/catalog/additional/CK_Components_6111_RoHS_Certificate.pdf",
        "allow_substitution": "No", "tracking": "No", "standards_version": "1.1",
        "source": "terra_sym", "dump_priority": 0, "tier": 2, "pin_count": "4",
        "temp_operating_min": -20, "temp_operating_max": 85, "current_rating": "16A",
        "switch_type": "rocker", "poles": 2, "throws": 2,
        "voltage_rating": "250 VAC", "actuation_force": None,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - switches harvested from terra_sym.kicad_sym",
        f"-- Native terra rows scripted from the terra_sym source. Generated by {Path(__file__).name}.",
        "-- dump_priority=0: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO switches ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
