#!/usr/bin/env python3
"""Bourns MH-series high-current chip ferrite bead family generator (datasheet-driven).

Generates the full Bourns MH-series family (sizes 1608/2029/3261 = 0603/0805/1206)
from the datasheet parked alongside this script (bourns_mh_ferrites_datasheet.pdf,
REV. 12/18). Supersedes the previously hand-migrated MH2029-800Y row.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ferrites_smt_generated_510_bourns_mh.sql")
CREATED_BY = Path(__file__).name

MANUFACTURER = "Bourns"
SYMBOL = "Device:FerriteBead_Small"
DATASHEET = "${TERRA_EDA_LIB}/db/tables/ferrites_smt/bourns_mh_ferrites_datasheet.pdf"

# Bourns size code -> (EIA package, KiCad footprint). Bourns codes are internal;
# the datasheet dimension drawing maps them to standard EIA sizes:
#   1608 = 1.6x0.8mm (0603), 2029 = 2.0x1.2mm (0805), 3261 = 3.2x1.6mm (1206).
SIZE = {
    "1608": ("0603", "Inductor_SMD:L_0603_1608Metric"),
    "2029": ("0805", "Inductor_SMD:L_0805_2012Metric"),
    "3261": ("1206", "Inductor_SMD:L_1206_3216Metric"),
}

# (mpn, size_code, impedance_ohm@100MHz, rdc_max_mohm, idc_max_A)
# Transcribed from the Bourns MH-series datasheet (REV. 12/18). All tolerance +/-25%.
FAMILY = [
    ("MH3261-601Y", "3261", 600, 100, 2.0),
    ("MH2029-070Y", "2029", 7, 30, 3.0),
    ("MH2029-100Y", "2029", 10, 10, 6.0),
    ("MH2029-300Y", "2029", 30, 25, 3.0),
    ("MH2029-400Y", "2029", 40, 20, 5.0),
    ("MH2029-600Y", "2029", 60, 20, 5.0),
    ("MH2029-800Y", "2029", 80, 40, 3.0),
    ("MH2029-101Y", "2029", 100, 100, 2.0),
    ("MH2029-121Y", "2029", 120, 100, 2.0),
    ("MH2029-151Y", "2029", 150, 100, 2.0),
    ("MH2029-221Y", "2029", 220, 100, 2.0),
    ("MH2029-301Y", "2029", 300, 200, 1.0),
    ("MH2029-401Y", "2029", 400, 100, 2.0),
    ("MH2029-471Y", "2029", 470, 200, 1.0),
    ("MH2029-601Y", "2029", 600, 200, 1.0),
    ("MH1608-100Y", "1608", 10, 10, 6.0),
    ("MH1608-300Y", "1608", 30, 40, 3.0),
    ("MH1608-600Y", "1608", 60, 40, 3.0),
    ("MH1608-800Y", "1608", 80, 40, 3.0),
    ("MH1608-101Y", "1608", 100, 40, 3.0),
    ("MH1608-121Y", "1608", 120, 100, 2.0),
    ("MH1608-151Y", "1608", 150, 100, 2.0),
    ("MH1608-181Y", "1608", 180, 100, 2.0),
    ("MH1608-221Y", "1608", 220, 100, 2.0),
    ("MH1608-301Y", "1608", 300, 200, 1.0),
    ("MH1608-471Y", "1608", 470, 200, 1.0),
    ("MH1608-601Y", "1608", 600, 200, 1.0),
]

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "tags", "pin_count",
    "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max",
    "impedance_at_freq", "dc_resistance", "current_rating", "tolerance",
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def row(mpn, size_code, imp, rdc, idc):
    package, footprint = SIZE[size_code]
    idc_s = f"{idc:g}"
    rec = {
        "unique_id": f"{MANUFACTURER}-{mpn}",
        "part_locator": f"ferrite-bead-{imp}r-{idc_s}a-{package}",
        "mpn": mpn, "manufacturer": MANUFACTURER, "package": package,
        "value": f"{imp}\u03a9 {idc_s}A",
        "description": (f"Bourns {mpn} high-current chip ferrite bead, "
                        f"{imp}\u03a9@100MHz \u00b125%, IDCmax={idc_s}A, "
                        f"RDCmax={rdc}m\u03a9, {package}"),
        "datasheet": DATASHEET,
        "manufacturer_link": "https://www.bourns.com",
        "kicad_symbol": SYMBOL, "kicad_footprint": footprint,
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "tags": "ferrite,bead", "pin_count": "2",
        "temp_operating_min": -55.0, "temp_operating_max": 125.0,
        "temp_storage_min": -55.0, "temp_storage_max": 125.0,
        "impedance_at_freq": f"{imp}\u03a9@100MHz",
        "dc_resistance": f"{rdc}m\u03a9", "current_rating": f"{idc_s}A",
        "tolerance": "25%",
    }
    vals = ", ".join(sql(rec[c]) for c in COLS)
    return f"INSERT INTO ferrites_smt ({', '.join(COLS)}) VALUES ({vals});"


def main():
    lines = [
        "-- Terra EDA Library - Bourns MH-series high-current chip ferrite beads",
        f"-- Datasheet-driven (REV. 12/18). Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    lines += [row(*p) for p in FAMILY]
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(FAMILY)} parts")


if __name__ == "__main__":
    main()
