#!/usr/bin/env python3
"""Harvest curated op-amps from the abc4-spiro-cart cartridge board into native terra.

OPA991 has no dedicated KiCad symbol; the standard single-op-amp SOT-23-5 symbol
Amplifier_Operational:OPA365xxDBV is used as a functionally-correct stand-in (same
pinout/package) -- the DB Value (OPA991) is what appears on the schematic.
Electrical parameters are populated in full from the datasheet.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("ic_opamp_generated_310_cart_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "amplifier_type", "input_type", "channels", "gain_bandwidth", "slew_rate",
    "input_offset", "input_offset_drift", "input_bias_current", "input_noise",
    "cmrr", "psrr", "quiescent_current", "output_current", "rail_to_rail",
    "positive_rail", "negative_rail", "supply_voltage_min", "supply_voltage_max",
    "power_rating",
]

PARTS = [
    {
        "unique_id": "Texas_Instruments-OPA991IDBVR",
        "part_locator": "ic-opamp-rrio-1ch-sot23-5",
        "mpn": "OPA991IDBVR", "manufacturer": "Texas Instruments",
        "package": "SOT-23-5", "value": "OPA991",
        "description": "Texas Instruments OPA991 40V rail-to-rail I/O single op-amp, SOT-23-5",
        "datasheet": "${TERRA_EDA_LIB}/datasheets/ti/opa991.pdf",
        "manufacturer_link": "https://www.ti.com/product/OPA991",
        "kicad_symbol": "Amplifier_Operational:OPA365xxDBV",
        "kicad_footprint": "Package_TO_SOT_SMD:SOT-23-5",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "keywords": "opamp,rrio,precision,40v,single,general-purpose", "pin_count": "5",
        "amplifier_type": "general-purpose", "input_type": "CMOS", "channels": 1,
        "gain_bandwidth": "4.5MHz", "slew_rate": "21V/µs",
        "input_offset": "±125µV", "input_offset_drift": "±0.3µV/°C",
        "input_bias_current": "±10pA", "input_noise": "10.8nV/√Hz",
        "cmrr": "130dB", "psrr": "120dB", "quiescent_current": "560µA",
        "output_current": "±75mA", "rail_to_rail": "RRIO",
        "positive_rail": "V+ +0.1V", "negative_rail": "V- -0.1V",
        "supply_voltage_min": 2.7, "supply_voltage_max": 40.0, "power_rating": None,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - op-amp harvest from abc4-spiro-cart cartridge board",
        f"-- Curated op-amps ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO ic_opamp ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
