#!/usr/bin/env python3
"""Harvest curated battery parts from the abc4-spiro mainboard into native terra.

The RRC2054 is an off-board smart Li-ion pack (no PCB footprint); it mates the
board via the RRC-MC20-90-10 connector (see connectors harvest).

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("batteries_generated_300_spiro_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords",
    "chemistry", "nominal_voltage_v", "capacity_ah", "energy_wh",
    "rechargeable", "smart_interface", "mates_with",
]

PARTS = [
    {
        "unique_id": "RRC_Power_Solutions-RRC2054", "part_locator": "battery-liion-14v4-3ah4",
        "mpn": "RRC2054", "manufacturer": "RRC Power Solutions", "value": "14.4V 3.4Ah",
        "description": "RRC2054 14.4V 3.4Ah 49Wh Li-ion smart battery pack (SMBus)",
        "datasheet": "https://www.rrc-ps.com/fileadmin/Dokumente/Data-Sheets/DS_RRC2054.pdf",
        "manufacturer_link": "https://www.rrc-ps.com",
        "kicad_symbol": "Device:Battery", "kicad_footprint": None,
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "keywords": "battery,li-ion,smart",
        "chemistry": "Li-ion", "nominal_voltage_v": 14.4, "capacity_ah": 3.4,
        "energy_wh": 49.0, "rechargeable": "yes", "smart_interface": "SMBus",
        "mates_with": "RRC-MC20-90-10",
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - batteries harvest from abc4-spiro mainboard",
        f"-- Curated battery parts ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO batteries ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
