CREATE TABLE diodes_zener (
    unique_id TEXT PRIMARY KEY,
    part_locator TEXT,
    mpn TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    variant TEXT,
    package TEXT,
    value TEXT,
    description TEXT,
    datasheet TEXT,
    manufacturer_link TEXT,
    kicad_symbol TEXT,
    kicad_footprint TEXT,
    altium_symbol TEXT,
    altium_footprint TEXT,
    lifecycle_status TEXT DEFAULT 'Active',
    rohs TEXT DEFAULT 'no',
    rohs_document_link TEXT,
    allow_substitution TEXT DEFAULT 'no',
    tracking TEXT DEFAULT 'no',
    standards_version TEXT DEFAULT 'v1.0',
    bom_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT,
    source TEXT DEFAULT 'static',
    dump_priority INTEGER DEFAULT 1,
    tier INTEGER DEFAULT 2,
    keywords TEXT DEFAULT '',
    sim_model_type TEXT,
    sim_device TEXT,
    sim_pins TEXT,
    sim_model_file TEXT,
    sim_params TEXT,
    pin_count TEXT,
    component_height TEXT,
    exclude_from_bom BOOLEAN NOT NULL DEFAULT 0,
    temp_operating_min REAL,
    temp_operating_max REAL,
    temp_storage_min REAL,
    temp_storage_max REAL,
    temp_soldering REAL,
    zener_voltage TEXT,          -- Vz nominal, e.g. '5.1V',
    zener_voltage_min REAL,      -- graded Vz min at test_current (V),
    zener_voltage_max REAL,      -- graded Vz max at test_current (V),
    tolerance TEXT,              -- '1%' (A) | '2%' (B) | '5%' (C),
    test_current TEXT,           -- Iz at which Vz is specified, e.g. '5mA',
    power_rating TEXT,           -- Ptot total power dissipation,
    forward_voltage TEXT,        -- Vf max,
    impedance_max REAL,          -- rdif max at the datasheet's quoted Iz (ohms),
    capacitance TEXT,            -- Cd max at 1 MHz, Vr=0 (pF),
    peak_reverse_current TEXT    -- Izsm non-repetitive peak reverse current (A)
);
