-- KiCad Symbol Library SQL Script
-- Legacy manually-created parts not yet covered by generators
--
-- INSERT-only SQL (no CREATE TABLE)
--

-- Insert symbols
BEGIN TRANSACTION;

INSERT INTO resistors_smt ("unique_id", "part_locator", "allow_substitution", "bom_comment", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "package", "power_rating", "rohs", "rohs_document_link", "sim_device", "sim_model_file", "sim_pins", "sim_model_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "altium_footprint", "altium_symbol", "variant", "source", "dump_priority") VALUES ('Yageo-MFR-25FTE52-330R', 'RES 330 ohm 1% metal film.Yageo', 'Yes', NULL, 'https://www.yageo.com/upload/media/product/productsearch/datasheet/lr/YAGEO%20MFR_datasheet_2022v2.pdf', 'Standard Component Template', 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal', 'Yageo', 'https://yageo.com', 'MFR-25FTE52-330R', 'metal film', 'Through hole axial', '1/4 W', 'yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/YAGO/YAGO-E-A0009164361/YAGO-E-A0009164361-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'R', NULL, '1=+ 2=-', NULL, '1.1', 'terra_sym:RES 330 ohm 1% metal film.Yageo', '-55C/155C', 'If applicable', 'If applicable', '50 ppm / C', '1%', 'No', '330 ohms', NULL, NULL, NULL, 'legacy', 1);
INSERT INTO resistors_smt ("unique_id", "part_locator", "allow_substitution", "bom_comment", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "package", "power_rating", "rohs", "rohs_document_link", "sim_device", "sim_model_file", "sim_pins", "sim_model_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "altium_footprint", "altium_symbol", "variant", "source", "dump_priority") VALUES ('Vishay-WSL2010R0400FEA18', 'RES Vishay 40 mOhm 1% 1W 2010', 'Yes', NULL, 'https://www.vishay.com/docs/31057/wslhigh.pdf', 'Resistor 40 mOhm 1%, 2010', 'Resistor_SMD:R_2010_5025Metric', 'Vishay', 'https://www.vishay.com/en/product/31057/', 'WSL2010R0400FEA18', 'Thick Film', '2010', '1/3 W', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'R', NULL, '1=+ 2=-', NULL, '1.1', 'terra_sym:RES Vishay 40 mOhm 1% 1W 2010', '-55C / +155C', 'standard', 'standard', '1200ppm/C', '1%', 'No', 'RES Vishay 40 mOhm 1% 1W 2010', NULL, NULL, NULL, 'legacy', 1);
INSERT INTO resistors_smt ("unique_id", "part_locator", "allow_substitution", "bom_comment", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "package", "power_rating", "rohs", "rohs_document_link", "sim_device", "sim_model_file", "sim_pins", "sim_model_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "altium_footprint", "altium_symbol", "variant", "source", "dump_priority") VALUES ('Vishay Dale-CRCW06035R60FKEAHP ', 'RES Vishay 5.6 ohm 1% 1/3W 0603', 'Yes', NULL, 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiq7prJmcT1AhVKkWoFHT1LB4QQFnoECAwQAQ&url=https%3A%2F%2Fwww.vishay.com%2Fdocs%2F20043%2Fcrcwhpe3.pdf&usg=AOvVaw3UfN7ma4DMQzQjN9bSQxYb', 'Resistor 5.6 ohm 1%, 1/3 W', 'Resistor_SMD:R_0603_1608Metric', 'Vishay Dale', 'https://www.vishay.com/product?docid=20043', 'CRCW06035R60FKEAHP ', 'Thick Film', '0603', '1/3 W', 'Yes', 'https://www.mouser.com/Search/CompliantByExemption?qs=Z21XLlfXTaipvM8tcgdKbw%3d%3d', 'R', NULL, '1=+ 2=-', NULL, '1.1', 'terra_sym:RES Vishay 5.6 ohm 1% 1/3W 0603', '-55C / +155C', 'standard', 'standard', '200ppm/K', '1%', 'No', 'RES Vishay 5.6 ohm 1{slash}3W 0603', NULL, NULL, NULL, 'legacy', 1);
INSERT INTO resistors_smt ("unique_id", "part_locator", "allow_substitution", "bom_comment", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "package", "power_rating", "rohs", "rohs_document_link", "sim_device", "sim_model_file", "sim_pins", "sim_model_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "altium_footprint", "altium_symbol", "variant", "source", "dump_priority") VALUES ('Vishay-WSL2512R0800FEA', 'RES Vishay 80 mOhm 1% 1W 2512', 'Yes', NULL, 'https://www.vishay.com/docs/30100/wsl.pdf', 'Resistor 40 mOhm 1%, 2010', 'Resistor_SMD:R_2512_6332Metric', 'Vishay', 'https://www.vishay.com/en/product/30100/', 'WSL2512R0800FEA', 'Thick Film', '2512', '1W', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'R', NULL, '1=+ 2=-', NULL, '1.1', 'terra_sym:RES Vishay 80 mOhm 1% 1W 2512', '-55C / +155C', 'standard', 'standard', '75ppm/C', '1%', 'No', 'RES Vishay 80 mOhm 1% 1W 2512', NULL, NULL, NULL, 'legacy', 1);
INSERT INTO resistors_smt ("unique_id", "part_locator", "allow_substitution", "bom_comment", "datasheet", "description", "kicad_footprint", "manufacturer", "manufacturer_link", "mpn", "composition", "package", "power_rating", "rohs", "rohs_document_link", "sim_device", "sim_model_file", "sim_pins", "sim_model_type", "standards_version", "kicad_symbol", "temp_operating", "temp_soldering", "temp_storage", "temp_coeff", "tolerance", "tracking", "value", "altium_footprint", "altium_symbol", "variant", "source", "dump_priority") VALUES ('Yageo- RL0805FR-070R04L ', 'RES Yageo 40 mOhm 1% 125 mW 0805', 'Yes', NULL, 'https://www.yageo.com/upload/media/product/products/datasheet/rchip/PYu-PT-Group_521_RoHS_L_2.pdf', 'Resistor 40 mOhm 1%, 0805', 'Resistor_SMD:R_0805_2012Metric', 'Yageo', 'https://www.yageo.com/en/Product/Index/rchip/current_sensing', ' RL0805FR-070R04L ', 'Thick Film', '0805', '1/3 W', 'Yes', 'https://www.mouser.com/catalog/additional/Yageo_6012_R_Chip_RoHS_Certificate.pdf', 'R', NULL, '1=+ 2=-', NULL, '1.1', 'terra_sym:RES Yageo 40 mOhm 1% 125 mW 0805', '-55C / +155C', 'standard', 'standard', '1200ppm/C', '1%', 'No', 'RES Yageo 40 mOhm 1% 125 mW 0805', NULL, NULL, NULL, 'legacy', 1);

COMMIT;
