CREATE TABLE resistors_smt (
    unique_id TEXT PRIMARY KEY,
    part_locator TEXT,
    mpn TEXT NOT NULL,
    manufacturer TEXT NOT NULL,
    variant TEXT,
    package TEXT,
    value TEXT,
    description TEXT,
    datasheet TEXT,
    manufacturer_link TEXT,
    kicad_symbol TEXT,
    kicad_footprint TEXT,
    altium_symbol TEXT,
    altium_footprint TEXT,
    lifecycle_status TEXT DEFAULT 'Active',
    rohs TEXT DEFAULT 'no',
    rohs_document_link TEXT,
    allow_substitution TEXT DEFAULT 'no',
    tracking TEXT DEFAULT 'no',
    standards_version TEXT DEFAULT 'v1.0',
    bom_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT,
    source TEXT DEFAULT 'static',
    dump_priority INTEGER DEFAULT 1,
    tier INTEGER DEFAULT 2,
    keywords TEXT DEFAULT '',
    sim_model_type TEXT,
    sim_device TEXT DEFAULT 'R',
    sim_pins TEXT DEFAULT '1=+ 2=-',
    sim_model_file TEXT,
    sim_params TEXT,
    pin_count TEXT,
    component_height TEXT,
    exclude_from_bom BOOLEAN NOT NULL DEFAULT 0,
    temp_operating_min REAL,
    temp_operating_max REAL,
    temp_storage_min REAL,
    temp_storage_max REAL,
    temp_soldering REAL,
    tolerance TEXT,
    power_rating TEXT,
    temp_coeff TEXT,
    voltage_rating TEXT,
    composition TEXT
);
