-- Terra EDA Library - resistors_smt Table Data (priority 1, source legacy)
-- Number of components: 5
-- Dump priority: 1
-- Source: legacy
-- Sorted by: unique_id
--
-- This file is auto-generated and suitable for git tracking.
-- Rows are sorted deterministically to ensure consistent diffs.
-- Table schema is in resistors_smt_0_schema.sql
--

BEGIN TRANSACTION;

INSERT INTO resistors_smt ("unique_id", "part_locator", "mpn", "manufacturer", "variant", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "source", "dump_priority", "tier", "keywords", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "pin_count", "component_height", "exclude_from_bom", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering", "tolerance", "power_rating", "temp_coeff", "voltage_rating", "composition") VALUES ('Vishay Dale-CRCW06035R60FKEAHP', 'RES Vishay 5.6 ohm 1% 1/3W 0603', 'CRCW06035R60FKEAHP', 'Vishay Dale', NULL, '0603', '5.6', 'Resistor 5.6 ohm 1%, 1/3 W', 'https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiq7prJmcT1AhVKkWoFHT1LB4QQFnoECAwQAQ&url=https%3A%2F%2Fwww.vishay.com%2Fdocs%2F20043%2Fcrcwhpe3.pdf&usg=AOvVaw3UfN7ma4DMQzQjN9bSQxYb', 'https://www.vishay.com/product?docid=20043', 'Device:R_US', 'Resistor_SMD:R_0603_1608Metric', NULL, NULL, 'Active', 'Yes', 'https://www.mouser.com/Search/CompliantByExemption?qs=Z21XLlfXTaipvM8tcgdKbw%3d%3d', 'Yes', 'No', '1.1', NULL, '2026-06-10 06:21:09', '2026-06-10 06:21:09', NULL, 'legacy', 1, 0, NULL, NULL, 'R', '1=+ 2=-', NULL, NULL, NULL, NULL, 0, -55.0, 155.0, NULL, NULL, NULL, '1%', '1/3 W', '200ppm/K', NULL, 'Thick Film');
INSERT INTO resistors_smt ("unique_id", "part_locator", "mpn", "manufacturer", "variant", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "source", "dump_priority", "tier", "keywords", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "pin_count", "component_height", "exclude_from_bom", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering", "tolerance", "power_rating", "temp_coeff", "voltage_rating", "composition") VALUES ('Vishay-WSL2010R0400FEA18', 'RES Vishay 40 mOhm 1% 1W 2010', 'WSL2010R0400FEA18', 'Vishay', NULL, '2010', '40m', 'Resistor 40 mOhm 1%, 2010', 'https://www.vishay.com/docs/31057/wslhigh.pdf', 'https://www.vishay.com/en/product/31057/', 'Device:R_US', 'Resistor_SMD:R_2010_5025Metric', NULL, NULL, 'Active', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'Yes', 'No', '1.1', NULL, '2026-06-10 06:21:09', '2026-06-10 06:21:09', NULL, 'legacy', 1, 0, NULL, NULL, 'R', '1=+ 2=-', NULL, NULL, NULL, NULL, 0, -55.0, 155.0, NULL, NULL, NULL, '1%', '1/3 W', '1200ppm/C', NULL, 'Thick Film');
INSERT INTO resistors_smt ("unique_id", "part_locator", "mpn", "manufacturer", "variant", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "source", "dump_priority", "tier", "keywords", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "pin_count", "component_height", "exclude_from_bom", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering", "tolerance", "power_rating", "temp_coeff", "voltage_rating", "composition") VALUES ('Vishay-WSL2512R0800FEA', 'RES Vishay 80 mOhm 1% 1W 2512', 'WSL2512R0800FEA', 'Vishay', NULL, '2512', '80m', 'Resistor 80 mOhm 1%, 2512', 'https://www.vishay.com/docs/30100/wsl.pdf', 'https://www.vishay.com/en/product/30100/', 'Device:R_US', 'Resistor_SMD:R_2512_6332Metric', NULL, NULL, 'Active', 'Yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/VISH/VISH-E-A0015053004/VISH-E-A0015053004-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'Yes', 'No', '1.1', NULL, '2026-06-10 06:21:09', '2026-06-10 06:21:09', NULL, 'legacy', 1, 0, NULL, NULL, 'R', '1=+ 2=-', NULL, NULL, NULL, NULL, 0, -55.0, 155.0, NULL, NULL, NULL, '1%', '1W', '75ppm/C', NULL, 'Thick Film');
INSERT INTO resistors_smt ("unique_id", "part_locator", "mpn", "manufacturer", "variant", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "source", "dump_priority", "tier", "keywords", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "pin_count", "component_height", "exclude_from_bom", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering", "tolerance", "power_rating", "temp_coeff", "voltage_rating", "composition") VALUES ('Yageo-MFR-25FTE52-330R', 'RES 330 ohm 1% metal film.Yageo', 'MFR-25FTE52-330R', 'Yageo', NULL, 'Through hole axial', '330', 'Resistor 330 ohm 1% metal film, axial', 'https://www.yageo.com/upload/media/product/productsearch/datasheet/lr/YAGEO%20MFR_datasheet_2022v2.pdf', 'https://yageo.com', 'Device:R_US', 'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P7.62mm_Horizontal', NULL, NULL, 'Active', 'yes', 'https://4donline.ihs.com/images/VipMasterIC/IC/YAGO/YAGO-E-A0009164361/YAGO-E-A0009164361-1.pdf?hkey=6D0214268300F1406B835FE51CB13195', 'Yes', 'No', '1.1', NULL, '2026-06-10 06:21:09', '2026-06-10 06:21:09', NULL, 'legacy', 1, 0, NULL, NULL, 'R', '1=+ 2=-', NULL, NULL, NULL, NULL, 0, -55.0, 155.0, NULL, NULL, NULL, '1%', '1/4 W', '50 ppm / C', NULL, 'metal film');
INSERT INTO resistors_smt ("unique_id", "part_locator", "mpn", "manufacturer", "variant", "package", "value", "description", "datasheet", "manufacturer_link", "kicad_symbol", "kicad_footprint", "altium_symbol", "altium_footprint", "lifecycle_status", "rohs", "rohs_document_link", "allow_substitution", "tracking", "standards_version", "bom_comment", "created_at", "updated_at", "created_by", "source", "dump_priority", "tier", "keywords", "sim_model_type", "sim_device", "sim_pins", "sim_model_file", "sim_params", "pin_count", "component_height", "exclude_from_bom", "temp_operating_min", "temp_operating_max", "temp_storage_min", "temp_storage_max", "temp_soldering", "tolerance", "power_rating", "temp_coeff", "voltage_rating", "composition") VALUES ('Yageo-RL0805FR-070R04L', 'RES Yageo 40 mOhm 1% 125 mW 0805', 'RL0805FR-070R04L', 'Yageo', NULL, '0805', '40m', 'Resistor 40 mOhm 1%, 0805', 'https://www.yageo.com/upload/media/product/products/datasheet/rchip/PYu-PT-Group_521_RoHS_L_2.pdf', 'https://www.yageo.com/en/Product/Index/rchip/current_sensing', 'Device:R_US', 'Resistor_SMD:R_0805_2012Metric', NULL, NULL, 'Active', 'Yes', 'https://www.mouser.com/catalog/additional/Yageo_6012_R_Chip_RoHS_Certificate.pdf', 'Yes', 'No', '1.1', NULL, '2026-06-10 06:21:09', '2026-06-10 06:21:09', NULL, 'legacy', 1, 0, NULL, NULL, 'R', '1=+ 2=-', NULL, NULL, NULL, NULL, 0, -55.0, 155.0, NULL, NULL, NULL, '1%', '1/3 W', '1200ppm/C', NULL, 'Thick Film');

COMMIT;
