#!/usr/bin/env python3
"""
Panasonic ERJ Series Current-Sensing (Low Resistance) Thick Film Resistor Generator
Generates comprehensive low-ohm resistors for Terra EDA Library

Covers all sub-series from the Panasonic ERJ low-resistance datasheet:
  - ERJ xLW/xBW/xCW: Double-sided high-power (milliohm range)
  - ERJ xBS/Q, xDS/Q: High-power type (sub-ohm to single-digit ohm)
  - ERJ xRS/Q: Standard type (sub-ohm to single-digit ohm)
  - ERJ Lxx: Low TCR type (milliohm range, fixed values)

Datasheet Reference:
  panasonic-erj.pdf (29-Sep-23)

MPN Formats:
  W-type:  ERJ{code}{tol}{value_4char}{pkg}     e.g. ERJ2BWFR047V
  SQ-type: ERJ{code}{range}{tol}{value_3char}{pkg}  e.g. ERJ3BSFR10V
  L-type:  ERJL{size}{valtype}{tol}{value_3char}{pkg}  e.g. ERJL14KF47MV
"""

import math
import re
import sys
import os
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


def parse_temp_range(s):
    """Extract two signed integers from a temperature range string.

    Handles forms like "-55°C to +125°C", "-55C / +155C", "-55C/155C".
    Returns a (min, max) pair of SQL literals (bare numbers). If two numbers
    cannot be parsed, returns ("NULL", "NULL").
    """
    if not s:
        return ("NULL", "NULL")
    nums = re.findall(r"[+-]?\d+", str(s))
    if len(nums) < 2:
        return ("NULL", "NULL")
    return (str(int(nums[0])), str(int(nums[1])))


def parse_temp_single(s):
    """Extract the leading signed integer from a temperature string.

    Handles forms like "260°C (10s max)". Returns an SQL literal (bare number),
    or "NULL" for non-numeric strings ("standard", "If applicable", "", None).
    """
    if not s:
        return "NULL"
    m = re.search(r"[+-]?\d+", str(s))
    if not m:
        return "NULL"
    return str(int(m.group()))

# ============================================================================
# ======================== USER CONFIGURATION ================================
# ============================================================================

# ======================== OUTPUT CONFIGURATION ========================
OUTPUT_FILE = "resistors_smt_generated_220_panasonic_erj_current_sense.sql"

# ======================== FAMILY ENABLE ========================
# Enable/disable entire sub-series families
FAMILY_ENABLE = {
    "LW": "yes",     # Double-sided ultra-low (5-10mΩ, fixed values)
    "BW": "yes",     # Double-sided low (10-100mΩ, E24)
    "CW": "yes",     # Double-sided low TCR (10-50mΩ, E24)
    "BS_Q": "yes",   # High power (0.1-9.1Ω, E24)
    "RS_Q": "yes",   # Standard (0.1-9.1Ω, E24)
    "L": "yes",      # Low TCR (20-100mΩ, fixed values)
}

# ======================== TOLERANCE ENABLE ========================
TOLERANCE_ENABLE = {
    "0.5%": "yes",   # D - only available on ERJ6D series
    "1%": "yes",     # F
    "2%": "yes",     # G
    "5%": "yes",     # J
}

# ============================================================================
# ======================== VENDOR SPECIFICATIONS =============================
# ============================================================================

# ======================== DATABASE METADATA ========================
SOURCE = None
DUMP_PRIORITY = 0

# ======================== MANUFACTURER SPECIFICATION ========================
MANUFACTURER = "Panasonic"
COMPOSITION = "Thick Film"
LIFECYCLE_STATUS = "Active"
ROHS_COMPLIANT = "Yes"
ALLOW_SUBSTITUTION = "Yes"
TRACKING = "No"

# ======================== URL TEMPLATES ========================
URL_TEMPLATES = {
    "datasheet": "${TERRA_EDA_LIB}/datasheets/panasonic/erj-series.pdf",
    "manufacturer_link": "https://industrial.panasonic.com/ww/products/pt/current-sensing-chip-resistors",
}

# ======================== STRING TEMPLATES ========================
STRING_TEMPLATES = {
    "description": "{manufacturer} {composition} current-sense resistor {value_readable} {tolerance} {power} {tempco} {package}",
    "part_locator": "res-{composition_slug}-current-sense-{value_lower}-{tolerance_lower}-{power_slug}-{package_lower}",
    "unique_id": "{manufacturer}-{mpn}",
    "temp_soldering": "270°C (10s max)",
    "temp_storage": "-55°C to +125°C",
}

# ======================== SQL TEMPLATES ========================
SQL_TEMPLATES = {
    "file_header": """-- Panasonic ERJ Series Current-Sensing (Low Resistance) Thick Film Resistors
-- Families: LW, BW, CW (double-sided), BS/Q (high-power), RS/Q (standard), L (low TCR)
-- Datasheet: {datasheet_url}
-- Symbol: {symbol_ref}
--
-- Generated by: {script_name}

BEGIN TRANSACTION;
""",

    "section_header": "-- === {section} ===",

    "insert": """INSERT INTO resistors_smt (unique_id, part_locator, mpn, manufacturer, variant, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, source, dump_priority, tier, tags, tolerance, power_rating, temp_coeff, voltage_rating, composition, temp_operating_min, temp_operating_max, temp_storage_min, temp_storage_max, temp_soldering, sim_device, sim_pins, lifecycle_status, rohs, allow_substitution, tracking, created_at, updated_at, created_by)
VALUES ('{unique_id}', '{part_locator}', '{mpn}', '{manufacturer}', {variant}, '{package}', '{value_sim}', '{description}', '{datasheet}', '{manufacturer_link}', '{kicad_symbol}', '{kicad_footprint}', {source}, {dump_priority}, {tier}, '{tags}', '{tolerance}', '{power_rating}', '{temp_coeff}', '{voltage_rating}', '{composition}', {temp_operating_min}, {temp_operating_max}, {temp_storage_min}, {temp_storage_max}, {temp_soldering}, '{sim_device}', '{sim_pins}', '{lifecycle_status}', '{rohs}', '{allow_substitution}', '{tracking}', '{created_at}', '{updated_at}', '{created_by}');""",

    "tag_insert": "INSERT INTO tags (unique_id, tag) VALUES ('{unique_id}', '{tag}');",

    "file_footer": """COMMIT;

-- Generated {total_parts} current-sense resistor parts""",
}

# ======================== SIMULATION PARAMETERS ========================
SIMULATION = {
    "device": "R",
    "pins": "1=+ 2=-",
}

# ======================== KICAD CONFIGURATION ========================
KICAD_CONFIG = {
    "symbol": "Device:R_US",
    "footprint_prefix": "Resistor_SMD:R_",
    "footprint_suffix": "Metric",
}

PACKAGE_METRIC = {
    "0402": "1005",
    "0603": "1608",
    "0805": "2012",
    "1206": "3216",
    "1210": "3225",
    "1812": "4532",
    "2010": "5025",
    "2512": "6332",
}

# ======================== TOLERANCE CODES ========================
TOLERANCE_CODES = {
    "0.5%": "D",
    "1%": "F",
    "2%": "G",
    "5%": "J",
}

# ============================================================================
# ======================== PRODUCT DATA ======================================
# ============================================================================
# Each entry in SERIES_DATA fully describes one sub-series.
# The generation loop iterates over these, expanding tolerances and values.
#
# Fields:
#   erj_code: code after "ERJ" in the MPN (e.g. "2LW", "3B", "L14")
#   family: which FAMILY_ENABLE key controls this
#   package: EIA package size
#   power: power rating string
#   mpn_type: "W" (4-char value), "SQ" (3-char with S/Q range), "L" (3-char milliohm)
#   range_letter: for SQ type, "S" or "Q" (None for others)
#   values: explicit list of ohm values (for fixed-value series)
#   e24_min/e24_max: for E24-generated ranges (in ohms)
#   tolerances: list of tolerance strings available for this sub-series
#   tcr: temperature coefficient string
#   packaging: packaging code (X, V, or U)
#   temp_operating: operating temperature range
#   voltage_rating: working voltage (computed from sqrt(P*R) but we store a nominal)

SERIES_DATA = [
    # ===================================================================
    # LW Series - Double-sided, ultra-low resistance, fixed values
    # MPN: ERJ{code}{tol}{value_4char}{pkg}
    # ===================================================================
    {
        "erj_code": "2LW", "family": "LW", "package": "0402", "power": "0.2W",
        "mpn_type": "W", "range_letter": None,
        "values": [0.010],
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +500ppm", "packaging": "X",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "3LW", "family": "LW", "package": "0603", "power": "0.25W",
        "mpn_type": "W", "range_letter": None,
        "values": [0.005],
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +700ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "3LW", "family": "LW", "package": "0603", "power": "0.25W",
        "mpn_type": "W", "range_letter": None,
        "values": [0.010],
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "6LW", "family": "LW", "package": "0805", "power": "0.5W",
        "mpn_type": "W", "range_letter": None,
        "values": [0.005, 0.006, 0.007, 0.008, 0.009],
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ===================================================================
    # BW Series - Double-sided, E24 milliohm range
    # MPN: ERJ{code}{tol}{value_4char}{pkg}
    # ===================================================================
    {
        "erj_code": "2BW", "family": "BW", "package": "0402", "power": "0.25W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 47, "e24_max_mohm": 100,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    # ERJ3BW: 20-100mΩ, split TCR
    {
        "erj_code": "3BW", "family": "BW", "package": "0603", "power": "0.33W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 20, "e24_max_mohm": 36,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "3BW", "family": "BW", "package": "0603", "power": "0.33W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 39, "e24_max_mohm": 100,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +150ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ6BW: 10-100mΩ, split TCR
    {
        "erj_code": "6BW", "family": "BW", "package": "0805", "power": "0.5W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 10, "e24_max_mohm": 13,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "6BW", "family": "BW", "package": "0805", "power": "0.5W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 15, "e24_max_mohm": 100,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ8BW: 10-100mΩ, split TCR
    {
        "erj_code": "8BW", "family": "BW", "package": "1206", "power": "1W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 10, "e24_max_mohm": 18,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "8BW", "family": "BW", "package": "1206", "power": "1W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 20, "e24_max_mohm": 43,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +150ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "8BW", "family": "BW", "package": "1206", "power": "1W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 47, "e24_max_mohm": 100,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +100ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ===================================================================
    # CW Series - Double-sided, low TCR, E24 milliohm range
    # MPN: ERJ{code}{tol}{value_4char}{pkg}
    # ===================================================================
    {
        "erj_code": "6CW", "family": "CW", "package": "0805", "power": "0.5W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 10, "e24_max_mohm": 30,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±75ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "8CW", "family": "CW", "package": "1206", "power": "1W",
        "mpn_type": "W", "range_letter": None,
        "e24_min_mohm": 10, "e24_max_mohm": 47,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±75ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },

    # ===================================================================
    # BS/Q Series - High power type, E24 sub-ohm to single-digit ohm
    # MPN: ERJ{code}{S/Q}{tol}{value_3char}{pkg}
    # ===================================================================

    # ERJ2B (0402, 0.166W) - S range
    {
        "erj_code": "2B", "family": "BS_Q", "package": "0402", "power": "1/6W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "X",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ2B - Q range
    {
        "erj_code": "2B", "family": "BS_Q", "package": "0402", "power": "1/6W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 1.0,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "X",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ3B (0603, 0.25W) - S range
    {
        "erj_code": "3B", "family": "BS_Q", "package": "0603", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ3B - Q range (0.22-0.91Ω)
    {
        "erj_code": "3B", "family": "BS_Q", "package": "0603", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ3B - Q range (1.0-9.1Ω)
    {
        "erj_code": "3B", "family": "BS_Q", "package": "0603", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ6D (0805, 0.5W) - S range (has ±0.5% option)
    {
        "erj_code": "6D", "family": "BS_Q", "package": "0805", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["0.5%", "1%", "2%", "5%"],
        "tcr": "0 to +150ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ6D - Q range (0.22-0.91Ω)
    {
        "erj_code": "6D", "family": "BS_Q", "package": "0805", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["0.5%", "1%", "2%", "5%"],
        "tcr": "0 to +100ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ6D - Q range (1.0-9.1Ω)
    {
        "erj_code": "6D", "family": "BS_Q", "package": "0805", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["0.5%", "1%", "2%", "5%"],
        "tcr": "±100ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ6B (0805, 0.33W) - S range
    {
        "erj_code": "6B", "family": "BS_Q", "package": "0805", "power": "0.33W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ6B - Q range (0.22-0.91Ω)
    {
        "erj_code": "6B", "family": "BS_Q", "package": "0805", "power": "0.33W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ6B - Q range (1.0-9.1Ω)
    {
        "erj_code": "6B", "family": "BS_Q", "package": "0805", "power": "0.33W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ8B (1206, 0.5W) - S range
    {
        "erj_code": "8B", "family": "BS_Q", "package": "1206", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ8B - Q range (0.22-0.91Ω)
    {
        "erj_code": "8B", "family": "BS_Q", "package": "1206", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ8B - Q range (1.0-9.1Ω)
    {
        "erj_code": "8B", "family": "BS_Q", "package": "1206", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ14B (1210, 0.5W) - S range
    {
        "erj_code": "14B", "family": "BS_Q", "package": "1210", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ14B - Q range (0.22-0.91Ω)
    {
        "erj_code": "14B", "family": "BS_Q", "package": "1210", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    # ERJ14B - Q range (1.0-9.1Ω)
    {
        "erj_code": "14B", "family": "BS_Q", "package": "1210", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },

    # ===================================================================
    # RS/Q Series - Standard type, E24 sub-ohm to single-digit ohm
    # MPN: ERJ{code}{S/Q}{tol}{value_3char}{pkg}
    # ===================================================================

    # ERJ3R (0603, 0.1W)
    {
        "erj_code": "3R", "family": "RS_Q", "package": "0603", "power": "0.1W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "3R", "family": "RS_Q", "package": "0603", "power": "0.1W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +300ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "3R", "family": "RS_Q", "package": "0603", "power": "0.1W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ6R (0805, 0.125W)
    {
        "erj_code": "6R", "family": "RS_Q", "package": "0805", "power": "0.125W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "6R", "family": "RS_Q", "package": "0805", "power": "0.125W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "6R", "family": "RS_Q", "package": "0805", "power": "0.125W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ8R (1206, 0.25W)
    {
        "erj_code": "8R", "family": "RS_Q", "package": "1206", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "8R", "family": "RS_Q", "package": "1206", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +250ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "8R", "family": "RS_Q", "package": "1206", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ14R (1210, 0.25W)
    {
        "erj_code": "14R", "family": "RS_Q", "package": "1210", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "14R", "family": "RS_Q", "package": "1210", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "14R", "family": "RS_Q", "package": "1210", "power": "0.25W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ12R (1812, 0.5W)
    {
        "erj_code": "12R", "family": "RS_Q", "package": "1812", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "12R", "family": "RS_Q", "package": "1812", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "12R", "family": "RS_Q", "package": "1812", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ12Z (2010, 0.5W)
    {
        "erj_code": "12Z", "family": "RS_Q", "package": "2010", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "12Z", "family": "RS_Q", "package": "2010", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "12Z", "family": "RS_Q", "package": "2010", "power": "0.5W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },

    # ERJ1TR (2512, 1W)
    {
        "erj_code": "1TR", "family": "RS_Q", "package": "2512", "power": "1W",
        "mpn_type": "SQ", "range_letter": "S",
        "e24_min": 0.10, "e24_max": 0.20,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "1TR", "family": "RS_Q", "package": "2512", "power": "1W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 0.22, "e24_max": 0.91,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "0 to +200ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },
    {
        "erj_code": "1TR", "family": "RS_Q", "package": "2512", "power": "1W",
        "mpn_type": "SQ", "range_letter": "Q",
        "e24_min": 1.0, "e24_max": 9.1,
        "tolerances": ["1%", "2%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +155°C",
    },

    # ===================================================================
    # L Series - Low TCR, fixed standard values
    # MPN: ERJL{size}{valtype}{tol}{value_3char}{pkg}
    # Standard values: 20, 22, 33, 39, 47, 50, 100 mΩ
    # ===================================================================
    {
        "erj_code": "L03", "family": "L", "package": "0603", "power": "0.2W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.047, 0.050, 0.100],
        "tolerances": ["1%", "5%"],
        "tcr": "±200ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "L06", "family": "L", "package": "0805", "power": "0.25W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.047, 0.050, 0.100],
        "tolerances": ["1%", "5%"],
        "tcr": "±100ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "L08", "family": "L", "package": "1206", "power": "0.33W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.047, 0.050, 0.100],
        "tolerances": ["1%", "5%"],
        "tcr": "±100ppm", "packaging": "V",
        "temp_operating": "-55°C to +125°C",
    },
    # ERJL14: 20-100mΩ, split TCR
    {
        "erj_code": "L14", "family": "L", "package": "1210", "power": "0.33W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.020, 0.022, 0.033, 0.039],
        "tolerances": ["1%", "5%"],
        "tcr": "±300ppm", "packaging": "U",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "L14", "family": "L", "package": "1210", "power": "0.33W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.047, 0.050, 0.100],
        "tolerances": ["1%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +125°C",
    },
    # ERJL12: 20-100mΩ, split TCR
    {
        "erj_code": "L12", "family": "L", "package": "1812", "power": "0.5W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.020, 0.022, 0.033, 0.039],
        "tolerances": ["1%", "5%"],
        "tcr": "±300ppm", "packaging": "U",
        "temp_operating": "-55°C to +125°C",
    },
    {
        "erj_code": "L12", "family": "L", "package": "1812", "power": "0.5W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.047, 0.050, 0.100],
        "tolerances": ["1%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +125°C",
    },
    # ERJL1D: 40-100mΩ
    {
        "erj_code": "L1D", "family": "L", "package": "2010", "power": "0.5W",
        "mpn_type": "L", "range_letter": None,
        "values": [0.047, 0.050, 0.100],
        "tolerances": ["1%", "5%"],
        "tcr": "±100ppm", "packaging": "U",
        "temp_operating": "-55°C to +125°C",
    },
]


# ============================================================================
# ======================== HELPER FUNCTIONS ==================================
# ============================================================================

# E24 lookup table (IEC 60063 standard values, 1.0-9.1 decade)
E24_TABLE = [1.0, 1.1, 1.2, 1.3, 1.5, 1.6, 1.8, 2.0, 2.2, 2.4,
             2.7, 3.0, 3.3, 3.6, 3.9, 4.3, 4.7, 5.1, 5.6, 6.2,
             6.8, 7.5, 8.2, 9.1]


def get_script_name() -> str:
    return Path(__file__).name


def get_last_commit_date() -> str:
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%ci", __file__],
            capture_output=True, text=True, cwd=Path(__file__).parent,
        )
        if result.returncode == 0 and result.stdout.strip():
            parts = result.stdout.strip().split()
            return parts[0] + " " + parts[1]
    except Exception:
        pass
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def get_build_date() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def get_kicad_footprint(package: str) -> str:
    metric = PACKAGE_METRIC.get(package, package)
    return f"{KICAD_CONFIG['footprint_prefix']}{package}_{metric}{KICAD_CONFIG['footprint_suffix']}"


def is_family_enabled(family: str) -> bool:
    return FAMILY_ENABLE.get(family, "no").lower() == "yes"


def is_tolerance_enabled(tol: str) -> bool:
    return TOLERANCE_ENABLE.get(tol, "no").lower() == "yes"


def generate_e24_milliohm_values(min_mohm: int, max_mohm: int) -> List[float]:
    """Generate E24 resistance values in a milliohm range, returning ohm values."""
    values = []
    for decade_exp in range(-2, 1):  # 0.01, 0.1, 1.0 decades
        for base in E24_TABLE:
            val_ohm = base * (10 ** decade_exp)
            val_mohm = round(val_ohm * 1000)
            if min_mohm <= val_mohm <= max_mohm:
                values.append(round(val_ohm, 6))
    return sorted(set(values))


def generate_e24_ohm_values(min_ohm: float, max_ohm: float) -> List[float]:
    """Generate E24 resistance values in an ohm range."""
    values = []
    for decade_exp in range(-1, 2):  # 0.1, 1.0, 10.0 decades
        for base in E24_TABLE:
            val = round(base * (10 ** decade_exp), 4)
            if min_ohm <= val <= max_ohm:
                values.append(val)
    return sorted(set(values))


def get_values_for_series(series: Dict) -> List[float]:
    """Get the list of resistance values (in ohms) for a series entry."""
    if "values" in series:
        return series["values"]
    elif "e24_min_mohm" in series:
        return generate_e24_milliohm_values(series["e24_min_mohm"], series["e24_max_mohm"])
    elif "e24_min" in series:
        return generate_e24_ohm_values(series["e24_min"], series["e24_max"])
    else:
        return []


# ======================== VALUE ENCODING ========================

# IEC/SPICE units for encode_resistance_spice
SPICE_UNITS = [
    ("m", -3),   # milli-ohm
    ("", 0),     # ohm
    ("K", 3),    # kilo-ohm
]


def encode_resistance_spice(value_ohm: float) -> str:
    """Encode resistance in SPICE format for the value field."""
    if value_ohm == 0:
        return "0"
    exp10 = math.log10(value_ohm)
    target = 3 * math.floor(exp10 / 3.0)
    marker, exp = min(SPICE_UNITS, key=lambda ue: abs(ue[1] - target))
    scale = 10 ** exp
    scaled = value_ohm / scale
    s = format(scaled, ".3f").rstrip("0").rstrip(".")
    return s + marker if marker else s


def encode_mpn_value_w(value_ohm: float) -> str:
    """Encode resistance for W-type MPNs (4-char, sub-ohm).

    Format: R + 3 digits representing milliohm with R as decimal.
    R005 = 5mΩ (0.005Ω), R047 = 47mΩ, R100 = 100mΩ
    """
    milliohm = round(value_ohm * 1000)
    return f"R{milliohm:03d}"


def encode_mpn_value_sq(value_ohm: float) -> str:
    """Encode resistance for SQ-type MPNs (3-char, IEC with R as decimal).

    Format: R as decimal point in ohm value.
    R10 = 0.10Ω, R22 = 0.22Ω, 1R0 = 1.0Ω, 9R1 = 9.1Ω
    """
    if value_ohm < 1.0:
        # Sub-ohm: R + 2 digits
        cents = round(value_ohm * 100)
        return f"R{cents:02d}"
    else:
        # 1Ω+: digit + R + digit
        whole = int(round(value_ohm, 1))
        frac = round((round(value_ohm, 1) - whole) * 10)
        return f"{whole}R{frac}"


def encode_mpn_value_l(value_ohm: float) -> str:
    """Encode resistance for L-type MPNs (3-char, milliohm with M marker).

    Format: milliohm value + M marker (for <100mΩ), or R{dd} for ≥100mΩ.
    20M = 20mΩ, 47M = 47mΩ, 50M = 50mΩ, R10 = 100mΩ (0.10Ω)
    """
    milliohm = round(value_ohm * 1000)
    if milliohm >= 100:
        # Use IEC ohm encoding: 100mΩ = 0.1Ω → R10
        cents = round(value_ohm * 100)
        return f"R{cents:02d}"
    else:
        return f"{milliohm:02d}M"


def format_mpn(value_ohm: float, series: Dict, tol_code: str) -> str:
    """Generate the full MPN for a part."""
    mpn_type = series["mpn_type"]
    erj_code = series["erj_code"]
    pkg = series["packaging"]

    if mpn_type == "W":
        value_code = encode_mpn_value_w(value_ohm)
        return f"ERJ{erj_code}{tol_code}{value_code}{pkg}"

    elif mpn_type == "SQ":
        range_letter = series["range_letter"]
        value_code = encode_mpn_value_sq(value_ohm)
        return f"ERJ{erj_code}{range_letter}{tol_code}{value_code}{pkg}"

    elif mpn_type == "L":
        value_code = encode_mpn_value_l(value_ohm)
        # L-series: ERJL{size}K{tol}{value}{pkg} where K = standard values
        size_code = erj_code[1:]  # Strip 'L' prefix → "03", "06", "14", "1D"
        return f"ERJL{size_code}K{tol_code}{value_code}{pkg}"

    raise ValueError(f"Unknown mpn_type: {mpn_type}")


# ============================================================================
# ======================== GENERATION FUNCTIONS ==============================
# ============================================================================

def generate_resistors() -> str:
    """Generate all current-sense resistor SQL statements."""
    script_name = get_script_name()
    created_date = get_last_commit_date()
    build_date = get_build_date()
    symbol_ref = KICAD_CONFIG["symbol"]
    source_sql = "NULL" if SOURCE is None else f"'{SOURCE}'"

    sql_lines = [SQL_TEMPLATES["file_header"].format(
        datasheet_url=URL_TEMPLATES["datasheet"],
        symbol_ref=symbol_ref,
        script_name=script_name,
    )]

    total_parts = 0
    seen_unique_ids = set()
    current_family = None

    for series in SERIES_DATA:
        family = series["family"]
        if not is_family_enabled(family):
            continue

        # Section header when family changes
        if family != current_family:
            current_family = family
            family_names = {
                "LW": "LW Series - Double-sided ultra-low resistance",
                "BW": "BW Series - Double-sided low resistance (E24)",
                "CW": "CW Series - Double-sided low TCR",
                "BS_Q": "BS/Q Series - High power type",
                "RS_Q": "RS/Q Series - Standard type",
                "L": "L Series - Low TCR type",
            }
            sql_lines.append("")
            sql_lines.append(SQL_TEMPLATES["section_header"].format(
                section=family_names.get(family, family)))

        values = get_values_for_series(series)
        if not values:
            continue

        for tol_str in series["tolerances"]:
            if not is_tolerance_enabled(tol_str):
                continue

            tol_code = TOLERANCE_CODES[tol_str]

            for value_ohm in values:
                mpn = format_mpn(value_ohm, series, tol_code)
                unique_id = STRING_TEMPLATES["unique_id"].format(
                    manufacturer=MANUFACTURER, mpn=mpn)

                # Skip duplicates (can occur with overlapping TCR ranges)
                if unique_id in seen_unique_ids:
                    continue
                seen_unique_ids.add(unique_id)

                value_spice = encode_resistance_spice(value_ohm)
                description = STRING_TEMPLATES["description"].format(
                    manufacturer=MANUFACTURER,
                    composition=COMPOSITION.lower(),
                    value_readable=value_spice,
                    tolerance=tol_str,
                    power=series["power"],
                    tempco=series["tcr"],
                    package=series["package"],
                )
                part_locator = STRING_TEMPLATES["part_locator"].format(
                    composition_slug="thick-film",
                    value_lower=value_spice.lower(),
                    tolerance_lower=tol_str.lower(),
                    power_slug=series["power"].replace("/", "_").lower(),
                    package_lower=series["package"].lower(),
                )

                # All current-sense parts are tier 3 (specialty)
                part_tier = 3

                sql_line = SQL_TEMPLATES["insert"].format(
                    unique_id=unique_id,
                    part_locator=part_locator,
                    mpn=mpn,
                    manufacturer=MANUFACTURER,
                    variant="NULL",
                    package=series["package"],
                    value_sim=value_spice,
                    description=description,
                    datasheet=URL_TEMPLATES["datasheet"],
                    manufacturer_link=URL_TEMPLATES["manufacturer_link"],
                    kicad_symbol=symbol_ref,
                    kicad_footprint=get_kicad_footprint(series["package"]),
                    source=source_sql,
                    dump_priority=DUMP_PRIORITY,
                    tier=part_tier,
                    tags="passive,current-sense",
                    tolerance=tol_str,
                    power_rating=series["power"],
                    temp_coeff=series["tcr"],
                    voltage_rating="",
                    composition=COMPOSITION,
                    temp_operating_min=parse_temp_range(series["temp_operating"])[0],
                    temp_operating_max=parse_temp_range(series["temp_operating"])[1],
                    temp_storage_min=parse_temp_range(STRING_TEMPLATES["temp_storage"])[0],
                    temp_storage_max=parse_temp_range(STRING_TEMPLATES["temp_storage"])[1],
                    temp_soldering=parse_temp_single(STRING_TEMPLATES["temp_soldering"]),
                    sim_device=SIMULATION["device"],
                    sim_pins=SIMULATION["pins"],
                    lifecycle_status=LIFECYCLE_STATUS,
                    rohs=ROHS_COMPLIANT,
                    allow_substitution=ALLOW_SUBSTITUTION,
                    tracking=TRACKING,
                    created_at=created_date,
                    updated_at=build_date,
                    created_by=script_name,
                )
                sql_lines.append(sql_line)
                sql_lines.append(SQL_TEMPLATES["tag_insert"].format(
                    unique_id=unique_id, tag="passive"))
                sql_lines.append(SQL_TEMPLATES["tag_insert"].format(
                    unique_id=unique_id, tag="current-sense"))
                total_parts += 1

    sql_lines.append("")
    sql_lines.append(SQL_TEMPLATES["file_footer"].format(total_parts=total_parts))
    return "\n".join(sql_lines)


def main():
    """Generate current-sense resistor SQL based on configuration."""
    print("Panasonic ERJ Series Current-Sensing Resistor Generator")
    print("=" * 55)

    enabled_families = [f for f, v in FAMILY_ENABLE.items() if v.lower() == "yes"]
    enabled_tols = [t for t, v in TOLERANCE_ENABLE.items() if v.lower() == "yes"]
    print(f"\nEnabled families: {', '.join(enabled_families)}")
    print(f"Enabled tolerances: {', '.join(enabled_tols)}")

    # Count series entries per family
    for family in enabled_families:
        count = sum(1 for s in SERIES_DATA if s["family"] == family)
        print(f"  {family}: {count} range entries")

    sql_content = generate_resistors()

    if not sql_content:
        print("\nNo parts generated. Check configuration.")
        sys.exit(1)

    with open(OUTPUT_FILE, "w") as f:
        f.write(sql_content)

    # Count from INSERT statements (each resistor has 1 INSERT INTO resistors_smt)
    total_parts = sql_content.count("INSERT INTO resistors_smt")
    print(f"\nGenerated: {OUTPUT_FILE}")
    print(f"Total parts generated: {total_parts}")


if __name__ == "__main__":
    main()
