#!/usr/bin/env python3
"""Harvest curated optoelectronic sensors from the abc4-spiro-cart board into terra.

OPB733TR has no standard KiCad symbol and a pin-specific reflective-sensor pinout, so
the curated symbol was migrated into the native lib terra-optoelectronics.kicad_sym
(and its footprint into terra-optoelectronics.pretty) -- a stand-in symbol would
mis-number the pads. Deep electrical params (If, Ic) are left NULL for the parametric
harvest pass.

Generated output (dump_priority=0, source=NULL) is not dumped to static SQL.
"""
from pathlib import Path

OUTPUT_FILE = Path(__file__).with_name("optoelectronics_sensor_generated_310_cart_harvest.sql")
CREATED_BY = Path(__file__).name

COLS = [
    "unique_id", "part_locator", "mpn", "manufacturer", "package", "value",
    "description", "datasheet", "manufacturer_link", "kicad_symbol",
    "kicad_footprint", "rohs", "allow_substitution", "tracking",
    "source", "dump_priority", "tier", "keywords", "pin_count",
    "sensor_type", "output_device", "emitter_type", "peak_wavelength_nm",
    "sensing_distance", "forward_current_ma", "collector_current_ma",
]

PARTS = [
    {
        "unique_id": "TT_Electronics-OPB733TR",
        "part_locator": "optosensor-reflective-phototransistor-smd",
        "mpn": "OPB733TR", "manufacturer": "TT Electronics",
        "package": "SMD", "value": "OPB733TR",
        "description": "TT Electronics/OPTEK OPB733TR reflective object sensor (890nm IR LED + NPN phototransistor), SMD",
        "datasheet": "${TERRA_EDA_LIB}/datasheets/tt-electronics/opb733.pdf",
        "manufacturer_link": "https://www.ttelectronics.com",
        "kicad_symbol": "terra-optoelectronics:OPB733TR",
        "kicad_footprint": "terra-optoelectronics:OPB733TR",
        "rohs": "Yes", "allow_substitution": "No", "tracking": "No",
        "source": None, "dump_priority": 0, "tier": 2,
        "keywords": "sensor,optical,reflective", "pin_count": "4",
        "sensor_type": "reflective", "output_device": "phototransistor",
        "emitter_type": "IR LED", "peak_wavelength_nm": 890.0,
        "sensing_distance": "0.4-1.0 in (10.2-25.4 mm)",
        "forward_current_ma": None, "collector_current_ma": None,
    },
]


def sql(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def main():
    lines = [
        "-- Terra EDA Library - optoelectronic sensor harvest from abc4-spiro-cart board",
        f"-- Curated sensors ported as native terra rows. Generated by {CREATED_BY}.",
        "-- dump_priority=0, source=NULL: regenerated, not dumped to static SQL.",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    for p in PARTS:
        vals = ", ".join(sql(p.get(c)) for c in COLS)
        lines.append(f"INSERT INTO optoelectronics_sensor ({', '.join(COLS)}) VALUES ({vals});")
    lines += ["", "COMMIT;", ""]
    OUTPUT_FILE.write_text("\n".join(lines))
    print(f"Generated {OUTPUT_FILE.name}: {len(PARTS)} parts")


if __name__ == "__main__":
    main()
