BEGIN TRANSACTION;

-- Legacy 3: migrated from leds table (source = terra_sym)
INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, temp_operating_min, temp_operating_max, temp_storage_min, temp_storage_max, supply_voltage_max, current_accuracy) VALUES ('Diodes, Inc-AL8843Q', 'LED DRIVER Diodes Inc AL8843Q', 'AL8843Q', 'Diodes, Inc', 'SO-8EP', 'LED DRIVER Diodes Inc AL8843Q', 'LED Driver 40V 3A Step-down', 'https://www.diodes.com/assets/Datasheets/AL8843Q.pdf', 'https://www.diodes.com/part/view/AL8843Q/', 'terra_sym:LED DRIVER Diodes Inc AL8843Q', 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias', 'Active', 'Yes', 'terra_sym', 1, 2, NULL, '8', -40, 150, -65, 150, 40.0, '4%');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, temp_operating_min, temp_operating_max, temp_storage_min, temp_storage_max, supply_voltage_max) VALUES ('Diodes, Inc-IS32LT3954', 'LED DRIVER Lumissil IS32LT3954', 'IS32LT3954', 'Diodes, Inc', 'SO-8EP', 'LED DRIVER Lumissil IS32LT3954', 'LED Driver 40V 3A Step-down', 'http://www.lumissil.com/assets/pdf/core/IS32LT3954_DS.pdf', 'http://www.lumissil.com/home', 'terra_sym:LED DRIVER Lumissil IS32LT3954', 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias', 'Active', 'Yes', 'terra_sym', 1, 2, NULL, '8', -40, 125, -65, 150, 42.0);

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, temp_operating_min, temp_operating_max, supply_voltage_max, current_accuracy) VALUES ('Texas Instruments-LM3410XMY/NOPB', 'LED DRIVER Texas Instruments LM3410XMY/NOPB', 'LM3410XMY/NOPB', 'Texas Instruments', 'MSOP Powerpad 8', 'LED DRIVER Texas Instruments LM3410XMY{slash}NOPB', 'LED Driver 24V 2.8A constant current w/internal compensation', 'https://www.ti.com/lit/gpn/LM3410', 'https://www.ti.com/store/ti/en/p/product/?p=LM3410XMY/NOPB', 'terra_sym:LED DRIVER Texas Instruments LM3410XMY/NOPB', 'terra_sym:LM3410XMY_NOPB', 'Active', 'Yes', 'terra_sym', 1, 2, NULL, '8', -40, 125, 10.0, '20%');

-- CERN 7: promoted from cern_analog_interface and cern_diodes (source = cern_promoted)
INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('MAXIM-MAX3967AETG', 'MAX3967AETG+', 'MAX3967AETG', 'MAXIM', 'QFN24', '270Mbps SFP LED Driver', '270Mbps SFP LED Driver', 'MAX3967AETG+.pdf', '', 'cern-analog-interface:MAX3967A', 'cern-ics-and-semiconductors-smd:QFN50P400X400X80-25N-S265', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '25', '0.8mm', 'analog');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('ST MICROELECTRONICS-STCS05DR', 'STCS05DR', 'STCS05DR', 'ST MICROELECTRONICS', 'SOIC8', '0.5A max Constant Current LED Driver', '0.5A max Constant Current LED Driver', 'STCS05DR.pdf', '', 'cern-analog-interface:STCS05', 'cern-ics-and-semiconductors-smd:SOIC127P600X175-8N', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '8', '1.75mm', 'analog');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('TEXAS INSTRUMENTS-TLC5920DL', 'TLC5920DLG4', 'TLC5920DL', 'TEXAS INSTRUMENTS', 'SSOP48', '16x8 Bit LED Driver/Controller', '16x8 Bit LED Driver/Controller', 'TLC5920DLG4.pdf', '', 'cern-analog-interface:TLC5920', 'cern-ics-and-semiconductors-smd:SOP64P1035X279-48N', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '48', '2.79mm', 'analog');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('TEXAS INSTRUMENTS-TLC5925IDW', 'TLC5925IDWR', 'TLC5925IDW', 'TEXAS INSTRUMENTS', 'SOIC24', 'Low-Power 16-Channel Constant-Current LED Sink Driver', 'Low-Power 16-Channel Constant-Current LED Sink Driver', 'TLC5925IDWR.pdf', '', 'cern-analog-interface:TLC5925', 'cern-ics-and-semiconductors-smd:SOIC127P1030X265-24N', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '24', '2.65mm', 'analog');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('TEXAS INSTRUMENTS-TLC5971RGE', 'TLC5971RGE', 'TLC5971RGE', 'TEXAS INSTRUMENTS', 'QFN24', '12-Channel, 16-Bit, Enhanced Spectrum, PWM, RGB, LED Driver With 3.3-V Linear Regulator', '12-Channel, 16-Bit, Enhanced Spectrum, PWM, RGB, LED Driver With 3.3-V Linear Regulator', 'TLC5971.pdf', '', 'cern-analog-interface:TLC5971RGE', 'cern-ics-and-semiconductors-smd:QFN50P400X400X100-25N-S280', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '25', '1.00mm', 'analog');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('ON SEMICONDUCTOR-NSI45015W', 'NSI45015W', 'NSI45015W', 'ON SEMICONDUCTOR', 'SOD-123', 'Constant Current Regulator & LED Driver (CRD)', 'Constant Current Regulator & LED Driver (CRD)', 'NSI45015W.pdf', '', 'cern-diodes:Diode CRD', 'cern-ics-and-semiconductors-smd:SOD3716X135N', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '2', '1.35mm', 'diode');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, tags) VALUES ('ON SEMICONDUCTOR-NSI50010Y', 'NSI50010YT1G', 'NSI50010Y', 'ON SEMICONDUCTOR', 'SOD-123', 'Constant Current Regulator & LED Driver (CRD)', 'Constant Current Regulator & LED Driver (CRD)', 'NSI50010YT1G.pdf', '', 'cern-diodes:Diode CRD', 'cern-ics-and-semiconductors-smd:SOD3716X135N', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '2', '1.35mm', 'diode');

COMMIT;
