BEGIN TRANSACTION;

-- Legacy 3: migrated from leds table (source = terra_sym)
INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, temp_operating_min, temp_operating_max, temp_storage_min, temp_storage_max, supply_voltage_max, current_accuracy, driver_topology, channels, output_current, supply_voltage_min, output_voltage_max, switching_freq, dimming_method, interface) VALUES ('Diodes, Inc-AL8843Q', 'LED DRIVER Diodes Inc AL8843Q', 'AL8843Q', 'Diodes, Inc', 'SO-8EP', 'LED DRIVER Diodes Inc AL8843Q', 'LED Driver 40V 3A Step-down', 'https://www.diodes.com/assets/Datasheets/AL8843Q.pdf', 'https://www.diodes.com/part/view/AL8843Q/', 'terra_sym:LED DRIVER Diodes Inc AL8843Q', 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias', 'Active', 'Yes', 'terra_sym', 1, 2, NULL, '8', -40, 150, -65, 150, 40.0, '±4%', 'buck', 1, '3A', 4.5, NULL, '1MHz', 'pwm', 'none');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, temp_operating_min, temp_operating_max, temp_storage_min, temp_storage_max, supply_voltage_max, driver_topology, channels, output_current, supply_voltage_min, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('Diodes, Inc-IS32LT3954', 'LED DRIVER Lumissil IS32LT3954', 'IS32LT3954', 'Diodes, Inc', 'SO-8EP', 'LED DRIVER Lumissil IS32LT3954', 'LED Driver 40V 3A Step-down', 'http://www.lumissil.com/assets/pdf/core/IS32LT3954_DS.pdf', 'http://www.lumissil.com/home', 'terra_sym:LED DRIVER Lumissil IS32LT3954', 'Package_SO:SOIC-8-1EP_3.9x4.9mm_P1.27mm_EP2.41x3.3mm_ThermalVias', 'Active', 'Yes', 'terra_sym', 1, 2, NULL, '8', -40, 125, -65, 150, 38.0, 'buck', 1, '3A', 4.5, NULL, NULL, 'pwm', 'none', NULL);

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, temp_operating_min, temp_operating_max, supply_voltage_max, current_accuracy, driver_topology, channels, output_current, supply_voltage_min, output_voltage_max, switching_freq, dimming_method, interface) VALUES ('Texas Instruments-LM3410XMY/NOPB', 'LED DRIVER Texas Instruments LM3410XMY/NOPB', 'LM3410XMY/NOPB', 'Texas Instruments', 'MSOP Powerpad 8', 'LED DRIVER Texas Instruments LM3410XMY{slash}NOPB', 'LED Driver 24V 2.8A constant current w/internal compensation', 'https://www.ti.com/lit/gpn/LM3410', 'https://www.ti.com/store/ti/en/p/product/?p=LM3410XMY/NOPB', 'terra_sym:LED DRIVER Texas Instruments LM3410XMY/NOPB', 'terra_sym:LM3410XMY_NOPB', 'Active', 'Yes', 'terra_sym', 1, 2, NULL, '8', -40, 125, 5.5, '20%', 'boost', 1, '2.8A', 2.7, '24V', '1.6MHz', 'pwm', 'none');

-- CERN 7: promoted from cern_analog_interface and cern_diodes (source = cern_promoted)
INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('MAXIM-MAX3967AETG', 'MAX3967AETG+', 'MAX3967AETG', 'MAXIM', 'QFN24', '270Mbps SFP LED Driver', '270Mbps SFP LED Driver', 'MAX3967AETG+.pdf', '', 'terra-led-drivers:MAX3967A', 'Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.65x2.65mm', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '25', '0.8mm', 'analog', 'linear', 1, '100mA', 2.97, 5.5, NULL, NULL, 'none', 'none', NULL);

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('ST MICROELECTRONICS-STCS05DR', 'STCS05DR', 'STCS05DR', 'ST MICROELECTRONICS', 'SOIC8', '0.5A max Constant Current LED Driver', '0.5A max Constant Current LED Driver', 'STCS05DR.pdf', '', 'terra-led-drivers:STCS05', 'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '8', '1.75mm', 'analog', 'linear', 1, '0.5A', 4.5, 40.0, NULL, NULL, 'pwm', 'none', '±10%');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('TEXAS INSTRUMENTS-TLC5920DL', 'TLC5920DLG4', 'TLC5920DL', 'TEXAS INSTRUMENTS', 'SSOP48', '16x8 Bit LED Driver/Controller', '16x8 Bit LED Driver/Controller', 'TLC5920DLG4.pdf', '', 'terra-led-drivers:TLC5920', 'Package_SO:SSOP-48_7.5x15.9mm_P0.635mm', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '48', '2.79mm', 'analog', 'linear', 16, '30mA', 4.5, 5.5, '5.5V', NULL, 'none', 'spi', '±6%');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('TEXAS INSTRUMENTS-TLC5925IDW', 'TLC5925IDWR', 'TLC5925IDW', 'TEXAS INSTRUMENTS', 'SOIC24', 'Low-Power 16-Channel Constant-Current LED Sink Driver', 'Low-Power 16-Channel Constant-Current LED Sink Driver', 'TLC5925IDWR.pdf', '', 'terra-led-drivers:TLC5925', 'Package_SO:SOIC-24W_7.5x15.4mm_P1.27mm', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '24', '2.65mm', 'analog', 'linear', 16, '45mA', 3.0, 5.5, '17V', NULL, 'none', 'spi', '±6%');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('TEXAS INSTRUMENTS-TLC5971RGE', 'TLC5971RGE', 'TLC5971RGE', 'TEXAS INSTRUMENTS', 'QFN24', '12-Channel, 16-Bit, Enhanced Spectrum, PWM, RGB, LED Driver With 3.3-V Linear Regulator', '12-Channel, 16-Bit, Enhanced Spectrum, PWM, RGB, LED Driver With 3.3-V Linear Regulator', 'TLC5971.pdf', '', 'Driver_LED:TLC5971RGE', 'Package_DFN_QFN:QFN-24-1EP_4x4mm_P0.5mm_EP2.65x2.65mm', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '25', '1.00mm', 'analog', 'linear', 12, '60mA', 3.0, 17.0, '17V', NULL, 'pwm', 'spi', '±1%');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('ON SEMICONDUCTOR-NSI45015W', 'NSI45015W', 'NSI45015W', 'ON SEMICONDUCTOR', 'SOD-123', 'Constant Current Regulator & LED Driver (CRD)', 'Constant Current Regulator & LED Driver (CRD)', 'NSI45015W.pdf', '', 'terra-diodes:Diode_CRD', 'Diode_SMD:D_SOD-123', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '2', '1.35mm', 'diode', 'linear', 1, '15mA', NULL, NULL, '45V', NULL, 'none', 'none', '±20%');

INSERT INTO led_drivers (unique_id, part_locator, mpn, manufacturer, package, value, description, datasheet, manufacturer_link, kicad_symbol, kicad_footprint, lifecycle_status, rohs, source, dump_priority, tier, created_by, pin_count, component_height, keywords, driver_topology, channels, output_current, supply_voltage_min, supply_voltage_max, output_voltage_max, switching_freq, dimming_method, interface, current_accuracy) VALUES ('ON SEMICONDUCTOR-NSI50010Y', 'NSI50010YT1G', 'NSI50010Y', 'ON SEMICONDUCTOR', 'SOD-123', 'Constant Current Regulator & LED Driver (CRD)', 'Constant Current Regulator & LED Driver (CRD)', 'NSI50010YT1G.pdf', '', 'terra-diodes:Diode_CRD', 'Diode_SMD:D_SOD-123', 'Active', 'no', 'cern_promoted', 1, 2, 'cern_import', '2', '1.35mm', 'diode', 'linear', 1, '10mA', NULL, 50.0, '50V', NULL, 'none', 'none', '±30%');

COMMIT;
